### ISSUE TITLE
Connections timed out

### ISSUE THREAD

**Issue by heqingwei** [relayrides/pushy#156]
I used pushy 0.4.3 to connect to APNS production enviroment.   During testing, I sent two messages: one using connection-2 and the other using connection-3. Both connections threw "Connection timed out"  Exception about 17 mins after the messages were sent out to APNs .  Finally my app didn't receive the messages at all.   So is there some stable problems with the pushy 0.4.3 or netty 4.0.26?

```
2015-03-11 17:41:22.208 INFO  [pool-2-thread-1]  com.aos.pns.PushService:120 - payload {"actionUri":"iosamap:\/\/rootmap?sourceApplication=XXX-1391","aps":{"alert":"XXX","badge":0}}, token: 105ecbfe3563b3b0415f3bab13503e5d9dbd06ad08aaefba68f12217921a2ca4 had sent out
2015-03-11 17:41:22.210 TRACE [nioEventLoopGroup-2-3]  com.relayrides.pushy.apns.ApnsConnection:540 - IOS-PushManager-connection-2 sending SendableApnsPushNotification [sequenceNumber=1, token=105ecbfe3563b3b0415f3bab13503e5d9dbd06ad08aaefba68f12217921a2ca4, payload={"actionUri":"iosamap:\/\/rootmap?sourceApplication=XXX-1391","aps":{"alert":"XXX","badge":0}}, deliveryInvalidation=Wed Mar 11 18:30:59 CST 2015]
2015-03-11 17:41:22.214 TRACE [nioEventLoopGroup-2-3]  com.relayrides.pushy.apns.ApnsConnection:549 - IOS-PushManager-connection-2 successfully wrote notification 1
2015-03-11 17:53:59.057 INFO  [pool-2-thread-1]  com.aos.pns.PushService:120 - payload {"actionUri":"iosamap:\/\/rootmap?sourceApplication=XXX-1392","aps":{"alert":"XXX","badge":0}}, token: 105ecbfe3563b3b0415f3bab13503e5d9dbd06ad08aaefba68f12217921a2ca4 had sent out
2015-03-11 17:53:59.058 TRACE [nioEventLoopGroup-2-4]  com.relayrides.pushy.apns.ApnsConnection:540 - IOS-PushManager-connection-3 sending SendableApnsPushNotification [sequenceNumber=1, token=105ecbfe3563b3b0415f3bab13503e5d9dbd06ad08aaefba68f12217921a2ca4, payload={"actionUri":"iosamap:\/\/rootmap?sourceApplication=XXX-1392","aps":{"alert":"XXX","badge":0}}, deliveryInvalidation=Wed Mar 11 18:50:59 CST 2015]
2015-03-11 17:53:59.059 TRACE [nioEventLoopGroup-2-4]  com.relayrides.pushy.apns.ApnsConnection:549 - IOS-PushManager-connection-3 successfully wrote notification 1
2015-03-11 17:58:40.099 DEBUG [nioEventLoopGroup-2-3]  com.relayrides.pushy.apns.ApnsConnection:313 - IOS-PushManager-connection-2 caught an exception.
java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
2015-03-11 17:58:40.103 TRACE [nioEventLoopGroup-2-3]  com.relayrides.pushy.apns.PushManager:759 - Connection closed: ApnsConnection [name=IOS-PushManager-connection-2]
2015-03-11 17:58:40.104 DEBUG [pool-1-thread-1]  com.relayrides.pushy.apns.ApnsConnection:453 - IOS-PushManager-connection-15 beginning connection process.
2015-03-11 17:58:40.454 DEBUG [nioEventLoopGroup-2-8]  com.relayrides.pushy.apns.ApnsConnection:460 - IOS-PushManager-connection-15 connected; waiting for TLS handshake.
2015-03-11 17:58:41.173 DEBUG [nioEventLoopGroup-2-8]  com.relayrides.pushy.apns.ApnsConnection:470 - IOS-PushManager-connection-15 successfully completed TLS handshake.
2015-03-11 17:58:41.173 TRACE [nioEventLoopGroup-2-8]  com.relayrides.pushy.apns.PushManager:693 - Connection succeeded: ApnsConnection [name=IOS-PushManager-connection-15]
2015-03-11 18:11:08.523 DEBUG [nioEventLoopGroup-2-4]  com.relayrides.pushy.apns.ApnsConnection:313 - IOS-PushManager-connection-3 caught an exception.
java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
2015-03-11 18:11:08.524 TRACE [nioEventLoopGroup-2-4]  com.relayrides.pushy.apns.PushManager:759 - Connection closed: ApnsConnection [name=IOS-PushManager-connection-3]
```

**Comment by jchambers** [comment]
It's hard for me to imagine that this is anything other than some transient connection issue (bad network connection, weird upstream issues, etc.). To clarify, has this happened in more cases than the ones you've described here? Is there a noticeable degradation in performance from previous versions?

**Comment by heqingwei** [comment]
I will do more investigation.

**Comment by jchambers** [comment]
@heqingwei Any news here?

**Comment by jchambers** [comment]
At this time, there doesn't seem to be much reason to believe that this is actually a bug or something within our control. Closing for now. @heqingwei, please post a comment here if there are any new developments and we'll reopen and investigate.

Thanks!

**Comment by ashokblend** [comment]
@jchambers even i faced this issue. I used dfr tool to reproduce the issue. eventhough i have set timeout as 120s this issue is coming for 50s
