### ISSUE TITLE
Connections time out

### ISSUE THREAD

**Issue by buyukim** [relayrides/pushy#162]
We picked up Pushy 0.4.2 a few months ago and started noticing intermittent issues with connection timeouts and our push messages would stop being sent out.  It seems that upgrading to Pushy 0.4.3 + Netty 4.0.26.Final has not fixed the issue.  Right now in production we are not seeing any new log statements when we try to send out push messages (stopped seeing them about 30 minutes ago).  We had Netty and Pushy logging levels turned up to TRACE.   Here are the last statements I can see in the logs: 

```
TRACE 2015-04-09 07:54:53,223 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-655 successfully wrote notification 4
DEBUG 2015-04-09 08:03:55,754 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-655 caught an exception.
java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:33)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:210)
        at sun.nio.ch.IOUtil.read(IOUtil.java:178)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:261)
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:796)
TRACE 2015-04-09 08:03:55,760 [nioEventLoopGroup-4-1] PushManager,Connection closed: ApnsConnection [name=PushManager-1-connection-655]
DEBUG 2015-04-09 08:03:55,760 [pool-4-thread-1] ApnsConnection,PushManager-1-connection-656 beginning connection process.
DEBUG 2015-04-09 08:03:55,855 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-656 connected; waiting for TLS handshake.
DEBUG 2015-04-09 08:03:56,066 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-656 successfully completed TLS handshake.
TRACE 2015-04-09 08:03:56,066 [nioEventLoopGroup-4-1] PushManager,Connection succeeded: ApnsConnection [name=PushManager-1-connection-656]
DEBUG 2015-04-09 09:03:56,068 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-656 will shut down gracefully due to inactivity.
DEBUG 2015-04-09 09:03:56,068 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-656 sending known-bad notification to shut down.
TRACE 2015-04-09 09:03:56,068 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-656 successfully wrote known-bad notification 1
DEBUG 2015-04-09 09:04:00,068 [nioEventLoopGroup-4-1] ApnsConnection,Graceful shutdown attempt for PushManager-1-connection-656 timed out; shutting down immediately.
TRACE 2015-04-09 09:04:00,068 [nioEventLoopGroup-4-1] PushManager,Connection closed: ApnsConnection [name=PushManager-1-connection-656]
DEBUG 2015-04-09 09:04:00,069 [pool-4-thread-1] ApnsConnection,PushManager-1-connection-657 beginning connection process.
DEBUG 2015-04-09 09:04:00,135 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 connected; waiting for TLS handshake.
DEBUG 2015-04-09 09:04:00,289 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 successfully completed TLS handshake.
TRACE 2015-04-09 09:04:00,289 [nioEventLoopGroup-4-1] PushManager,Connection succeeded: ApnsConnection [name=PushManager-1-connection-657]
TRACE 2015-04-09 09:06:29,620 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 sending SendableApnsPushNotification [sequenceNumber=1, token=XXX, payload={"aa":{"sentDate":"2015-04-09T13:06:29.617Z",. . .},"aps":{"alert":". . ."}}, deliveryInvalidation=Sun Apr 12 09:06:29 EDT 2015]
TRACE 2015-04-09 09:06:29,620 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 successfully wrote notification 1
TRACE 2015-04-09 09:06:29,669 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 sending SendableApnsPushNotification [sequenceNumber=2, token=XXX, payload={"aa":{"sentDate":"2015-04-09T13:06:29.665Z","title":". . ."},"aps":{"alert":". . ."}}, deliveryInvalidation=Sun Apr 12 09:06:29 EDT 2015]
TRACE 2015-04-09 09:06:29,669 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 successfully wrote notification 2
TRACE 2015-04-09 09:07:11,791 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 sending SendableApnsPushNotification [sequenceNumber=3, token=XXX, payload={"aa":{"sentDate":"2015-04-09T13:07:11.782Z","title":". . .","id":". . ."},"aps":{"alert":". . ."}}, deliveryInvalidation=Sun Apr 12 09:07:11 EDT 2015]
TRACE 2015-04-09 09:07:11,791 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 successfully wrote notification 3
TRACE 2015-04-09 09:07:11,828 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 sending SendableApnsPushNotification [sequenceNumber=4, token=XXX, payload={"aa":{"sentDate":"2015-04-09T13:07:11.821Z","title":". . ."},"aps":{"alert":". . ."}}, deliveryInvalidation=Sun Apr 12 09:07:11 EDT 2015]
TRACE 2015-04-09 09:07:11,828 [nioEventLoopGroup-4-1] ApnsConnection,PushManager-1-connection-657 successfully wrote notification 4
```

Here is our config:

apple.push.manager.concurrentConnections=5
apple.push.manager.maxConnectionSendLimit=1400
apple.push.manager.connectionInactivityReconnectLimit=3600

I am wondering if our inactivity limit is too short.

The last time this happened I also tried to execute shutdown with a timeout of 4 seconds and noticed that the shutdown never finished and ended up having to restart the JVM to restore connectivity.  I am going to try to generate a thread dump but is there anything else I should try to gather?

Thanks,
Mark

**Comment by jchambers** [comment]
This appears to be mostly a duplicate of #156. I don't think anything is actually wrong here; sometimes connections time out for reasons beyond our control.

To answer your specific questions, though, it appears that your connections will close after an hour of inactivity. That's probably too long if you're not sending notifications frequently; you might look for something closer to a single-digit number of minutes.

> The last time this happened I also tried to execute shutdown with a timeout of 4 seconds and noticed that the shutdown never finished and ended up having to restart the JVM to restore connectivity.

I'm not sure why you'd need to restart the JVM, but 4 seconds is probably cutting it a little close. If that happens again, please open a separate issue so we can dig into it.

**Comment by buyukim** [comment]
I understand that connections can timeout, but it should recover after the inactivity period.  I am saying that it never recovers and we are forced to restart our JVM to restore push connectivity

**Comment by buyukim** [comment]
The last incident in February resulted in no push alerts being sent out over multiple days (config was the same as above)
