### ISSUE TITLE
Closed Channel Exception with valid p12

### ISSUE THREAD

**Issue by tonicebrian** [relayrides/pushy#187]
Hi,
  
   I'm using a simple test driver program for testing the reception of notifications but I'm not able to connect. This is my Scala program, nothing special, and the Listeners are just printing stuff:

```scala
object Driver extends App {

  // Setup
  val config = ConfigFactory.load()

  val logger = LoggerFactory.getLogger(Driver.getClass)

  val inputStream = getClass.getResourceAsStream(config.getString("apn.key.path"))
  val pm = new PushManager[SimpleApnsPushNotification](
    ApnsEnvironment.getSandboxEnvironment,
    SSLContextUtil.createDefaultSSLContext(inputStream, config.getString("apn.key.password")),
    null, // Optional: custom event loop group
    null, // Optional: custom ExecutorService for calling listeners
    new SynchronousQueue[SimpleApnsPushNotification](), // Optional: custom BlockingQueue implementation
    new PushManagerConfiguration(),
    "SimplePushManager");

  pm.registerRejectedNotificationListener(new RejectionListener)
  pm.registerFailedConnectionListener(new MyFailedConnectionListener)
  pm.registerExpiredTokenListener(new MyExpiredTokensListener)

  pm.start()

  // Send message
  val IPHONE_TOKEN = "85f3afe8c1e025778cc5aa67869d2023a446cef1b18b51cc73f02d151a81c690"
  val token = TokenUtil.tokenStringToByteArray(IPHONE_TOKEN)

  val payloadBuilder = new ApnsPayloadBuilder
  payloadBuilder.setAlertBody("Hola IOS")
  val payload = payloadBuilder.buildWithDefaultMaximumLength()
  val notification = new SimpleApnsPushNotification(token, payload)

  logger.info("Notification to send: " + notification.toString)

  pm.getQueue.put(notification)
  // Turn down
  pm.shutdown()
}
```

The p12 certificates that are being loaded are working ok if I check manually. I checked it by issuing the following commands
```
$ openssl x509 -in aps_development.cer -inform der -out PushChatCert.pem
$ openssl pkcs12 -nocerts -out PushChatKey.pem -in PushChatKey.p12
$ openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert PushChatCert.pem -key PushChatKey.pem
```

But I'm getting this logs:
```
*** (c.r.pushy.apns.ApnsConnection) SimplePushManager-connection-9 beginning connection process.
*** (c.r.pushy.apns.ApnsConnection) SimplePushManager-connection-9 connected; waiting for TLS handshake.
*** (c.r.pushy.apns.ApnsConnection) SimplePushManager-connection-9 caught an exception.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_45]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_45]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_45]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_45]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_45]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-all-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.26.Final.jar:4.0.26.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
*** (c.r.pushy.apns.ApnsConnection) SimplePushManager-connection-9 failed to complete TLS handshake with APNs gateway.
java.nio.channels.ClosedChannelException: null
```

How can I check diagnose what is going wrong? It seems like something is wrong with the TTLs but I'm able to successfully send notifications with a small PHP utility and using those certs.

By the way, PHP needs a composite PEM with the .cer and .p12 in order to communicate. Am I missing something by just specifying the plain .p12 file?

**Comment by jchambers** [comment]
You're almost certainly using a production certificate in a sandbox environment or vice versa.

**Comment by adamaviner** [comment]
Had the same problem, the issue is, as you suspected, an incomplete .p12 file the [tutorial](http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1) we followed explains how to use the keys in php, but fails to mention that you can just export both the cert and private key together ([as explained here](http://faq.appaloosa-store.com/knowledgebase/articles/61785-how-to-generate-push-notification-p12-file)) from the keychain to create a complete .p12 file, which can be used by pushy.

**Comment by tonicebrian** [comment]
I confirm @adamaviner explanation. I was just exporting the key because that's what's needed for the PHP tutorial but pushy needs both elements. By exporting the combined key pushy was able to send notifications with the above code.

**Comment by jchambers** [comment]
Cool. Thanks for the update!
