### ISSUE TITLE
CloseAfterInactivityTime not working as expected

### ISSUE THREAD

**Issue by tanersener** [relayrides/pushy#191]
Hi,

I'm using pushy 0.4.3 to send APNS notifications. My configuration uses CloseAfterInactivityTime (set to 300 seconds = 5 minutes) to detect inactivity and renew the connection. Sometimes the following case occurs.

After 5 minutes of inactivity a known-bad notification is written. 
```
2015-09-10 14:46:49 c.r.p.a.ApnsConnection [DEBUG] [nioEventLoopGroup-13-1] 4BXY88ZM-connection-269 will shut down gracefully due to inactivity.
2015-09-10 14:46:49 c.r.p.a.ApnsConnection [DEBUG] [nioEventLoopGroup-13-1] 4BXY88ZM-connection-269 sending known-bad notification to shut down.
2015-09-10 14:46:49 c.r.p.a.ApnsConnection [TRACE] [nioEventLoopGroup-13-1] 4BXY88ZM-connection-269 successfully wrote known-bad notification 1
```

But reply of this write operation is not received immediately and read operation times out. The problem is; timeout is received after 17 minutes. So actually my 5 minutes idle time does not work as expected.

```
2015-09-10 15:03:45 c.r.p.a.ApnsConnection [DEBUG] [nioEventLoopGroup-13-1] 4BXY88ZM-connection-269 caught an exception.
java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method) ~[na:1.6.0_45]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21) ~[na:1.6.0_45]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198) ~[na:1.6.0_45]
	at sun.nio.ch.IOUtil.read(IOUtil.java:166) ~[na:1.6.0_45]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245) ~[na:1.6.0_45]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[stormjar.jar:na]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[stormjar.jar:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241) ~[stormjar.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[stormjar.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [stormjar.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [stormjar.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [stormjar.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [stormjar.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [stormjar.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [stormjar.jar:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
```

So I have these questions?

1) How about adding a socket timeout setting for write/read operations so I can configure it to prevent this case? 

2) When and idle connection is detected and will be closed, why do you try to write something (bad-known notification)? Wouldn't be easier to simply close it? Writing known-bad notification seems an unnecessary task and the root cause of this case in my opinion.

Thanks

**Comment by jchambers** [comment]
> When and idle connection is detected and will be closed, why do you try to write something (bad-known notification)?

Because the APNs gateway never sends us anything unless it receives a bad notification, there's no way for us to tell the difference between "we *are not* going to get more traffic from the gateway" and "we *have not yet* received any traffic from the gateway." As a consequence, there's no way to know when it's "safe" to close the connection.

> Wouldn't be easier to simply close it?

Yes, but then we might fail to let callers know that (for example) all of the notifications they just sent were actually rejected.

> Writing known-bad notification seems an unnecessary task and the root cause of this case in my opinion.

Believe me: I wish we didn't have to do this. We're all looking forward to [APNs via HTTP/2](https://github.com/relayrides/pushy/issues/184) when that comes out.

> How about adding a socket timeout setting for write/read operations so I can configure it to prevent this case?

We DO have a write timeout for the whole shut-down-via-a-known-bad-notification scheme. Please see [`ApnsConnectionConfiguration#setGracefulShutdownTimeout`](http://relayrides.github.io/pushy/apidocs/0.4/com/relayrides/pushy/apns/ApnsConnectionConfiguration.html#setGracefulShutdownTimeout(java.lang.Integer)) for additional details.
