### ISSUE TITLE
Control connection retry rate

### ISSUE THREAD

**Issue by salemsaberhagen** [relayrides/pushy#195]
I am using Pushy 0.4.3 in a Play app (just one instance/connection for the whole app) with the same setup specified in [Using Pushy](https://github.com/relayrides/pushy#using-pushy), with a listener to failed connections:

	pushManager.registerFailedConnectionListener((pushManager, throwable) -> {
		logger.error("Got exception", throwable);
	});

When the network goes down, the logging generated is HUGE. It seems that Pushy just retries again and again and again to reconnect without any delay between the retries.

Also, when starting pushy and the network connection is already down I get a different exception logged by Netty, in addition to the above listener:

	Failed to fail the promise because it's done already: DefaultChannelPromise@6af66ab7(failure(java.net.SocketException: Network is unreachable: gateway.sandbox.push.apple.com/17.172.232.18:2195)
	io.netty.channel.ChannelException: java.net.SocketException: Socket is closed
		at io.netty.channel.socket.DefaultSocketChannelConfig.getSoLinger(DefaultSocketChannelConfig.java:150) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe.closeExecutor(NioSocketChannel.java:335) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:568) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannel$AbstractUnsafe.closeIfClosed(AbstractChannel.java:797) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:236) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1089) ~[netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:543) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:528) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.handler.ssl.SslHandler.connect(SslHandler.java:415) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:543) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:528) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:543) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:528) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:510) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:909) [netty-all-4.0.26.Final.jar:4.0.26.Final]
		at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:203) [netty-all-4.0.26.Final.jar:4.0.26.Final]

If this is the case, there is any way to add a retry interval? I know that I can simply disable the logging in Netty and Pushy or just log one in 10000 errors for example, but it does not seem very clean...

**Comment by jchambers** [comment]
This is fixed in #169, which we hope to release shortly. Thanks for the report!

**Comment by vkolotov** [comment]
We have the same issue. We are looking forward to seeing the fix in master... For now we just enabled logback filter to filter out repetitive netty and pushy messages:

<turboFilter class="ch.qos.logback.classic.turbo.DuplicateMessageFilter"/>

**Comment by peterallday** [comment]
Any idea when this release will be out?
