### ISSUE TITLE
AbstractMethodError when trying to connect to APNs Gaterway

### ISSUE THREAD

**Issue by dorheini** [relayrides/pushy#246]
Hi.
I'm having issues with using pushy for push notifications.
i'm using java 7 and tomcat 7.
i have a simple web service on tomcat which sends push notification when directing to specific url.
When doing the following:
`final Future<Void> connectFuture = client.connect(ApnsClient.DEVELOPMENT_APNS_HOST);`

i get:
```
io.netty.handler.codec.DecoderException: java.lang.AbstractMethodError
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:439)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:162)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:924)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.OpenSslEngine.readPlaintextData(OpenSslEngine.java:358)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:703)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:809)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1092)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:976)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
	... 14 more
2016-02-25 13:14:24 WARN  ApplicationProtocolNegotiationHandler:146 - [id: 0xe4d96d17, L:/10.8.1.22:53085 - R:api.development.push.apple.com/17.172.238.203:443] Failed to select the application-level protocol:
io.netty.handler.codec.DecoderException: java.lang.AbstractMethodError
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:439)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:162)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:924)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.OpenSslEngine.readPlaintextData(OpenSslEngine.java:358)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:703)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:809)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1092)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:976)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
	... 14 more
2016-02-25 13:14:24 WARN  ApplicationProtocolNegotiationHandler:146 - [id: 0xe4d96d17, L:/10.8.1.22:53085 - R:api.development.push.apple.com/17.172.238.203:443] TLS handshake failed:
javax.net.ssl.SSLException: engine closed
2016-02-25 13:14:24 WARN  ApplicationProtocolNegotiationHandler:146 - [id: 0xe4d96d17, L:/10.8.1.22:53085 - R:api.development.push.apple.com/17.172.238.203:443] TLS handshake failed:
javax.net.ssl.SSLException: engine closed
```

i installed OpenSSL version 1.0.2f and i'm running the above on OSX.
i also added netty-tcnative as dependency to my project as follows:
```
<dependency>
      		<groupId>io.netty</groupId>
      		<artifactId>netty-tcnative</artifactId>
      		<version>1.1.33.Fork14</version>
      		<classifier>osx-x86_64</classifier>
    	</dependency>
```
Cant figure out the problem but it seems that something wrong with openssl...
any idea?

**Comment by ylgrgyq** [comment]
I got this problem too. I found that pushy 0.5.2 must use netty-tcnative 1.1.33.Fork13 with classifier osx-x86_64, only pushy 0.6-SNAPSHOT can use 1.1.33.Fork14 with classifier osx-x86_64

**Comment by kduhyun** [comment]
@dorheini @ylgrgyq 
I had a problem like that.
Here is my solution.  The main reason is netty-codec-http2's version is not match with netty-tcnative's version.

pom.xml

	<properties>
		<tcnative.classifier>osx-x86_64</tcnative.classifier>
	</properties>

		<dependency>
			<groupId>com.relayrides</groupId>
			<artifactId>pushy</artifactId>
			<version>0.5.2</version>
		</dependency>

		
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http2</artifactId>
			<version>4.1.0.CR3</version>
			<scope>compile</scope>
		</dependency>

		
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative</artifactId>
			<version>1.1.33.Fork14</version>
			<classifier>${tcnative.classifier}</classifier>
		</dependency>

**Comment by jchambers** [comment]
I'll try to make the netty-tcnative version requirements clearer in the README (I wasn't really aware that there WERE such specific requirements until these issues started rolling in). Additionally, I've filed a [request for more detailed docs](https://github.com/netty/netty-tcnative/issues/115) with the netty-tcnative folks.

I suspect that adding netty-tcnative to the test matrix (#232) will help a lot.

**Comment by karayv** [comment]
Still reproducible with 1.1.33.Fork15. I've put back 1.1.33.Fork13. 

PS. It was tricky to make the library work. I have older Mac OSx and needed to upgrade OpenSSL.
In case anyone needs working gradle script, here is mine:

`apply plugin: 'com.google.osdetector'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gradle:osdetector-gradle-plugin:1.4.0'
    }
}

dependencies {
    // project dependencies here

    // https://github.com/relayrides/pushy
    compile("com.relayrides:pushy:0.5.2")
    compile("io.netty:netty-tcnative:1.1.33.Fork13:$osdetector.classifier")
    runtime("org.eclipse.jetty.alpn:alpn-api:1.1.2.v20150522")
}
`
