### ISSUE TITLE
Pushy 0.5.2 incompatible with netty-tcnative 1.1.33.Fork14

### ISSUE THREAD

**Issue by vargusz** [relayrides/pushy#249]
Pushy 0.5.2 is incompatible with netty-tcnative 1.1.33.Fork14. It was working fine with 1.1.33.Fork13.
This is caused by the fact that Netty 4.1.0.CR2 is incompatible with this new version of netty-tcnative.
The following exception is thrown when using these two versions together.

Upgrading to Netty 4.1.0.CR3 (as in commit 10d788ac2e78ddb999cd92a2c3590480a2ff1b74) resolves the issue.
This incompatibility should either be [documented](https://github.com/relayrides/pushy/blob/master/README.md#using-openssl-as-an-ssl-provider) (e.g. using a version matrix), or maybe you could release a new minor version of Pushy that includes 10d788ac2e78ddb999cd92a2c3590480a2ff1b74. Thank you!

```
io.netty.handler.codec.DecoderException: java.lang.AbstractMethodError
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:439)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:162)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:924)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
Caused by: java.lang.AbstractMethodError
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.OpenSslEngine.readPlaintextData(OpenSslEngine.java:358)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:703)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:809)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1092)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:976)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
```

**Comment by jchambers** [comment]
Seems reasonable to me. I'm hoping to solve this comprehensively by changing our recommendation to statically-linked netty-tcnative (see #240), but that means we're waiting for Netty 4.1 CR4. We'll take a smaller step if it looks like CR4 won't be out for a while.

**Comment by jchambers** [comment]
Netty 4.1 CR4 is out, so I expect to clear this out shortly.

**Comment by jchambers** [comment]
…and now netty-tcnative fork 15 is out, too!

**Comment by jchambers** [comment]
Still waiting for system requirements to get documented upstream (see https://github.com/netty/netty/issues/4808). Additionally, I've run into a problem when just trying to get things working with the latest versions of `netty` and `netty-tcnative`: https://github.com/netty/netty/issues/5052

**Comment by jchambers** [comment]
Evidently, the uber-jar won't be out until fork 16. Pulling this out of the 0.6 milestone, since I think we ought to release that now (and we can update the README after release).

**Comment by jchambers** [comment]
Added an explicit version callout in aacdf77. We'll do further updates whenever fork16 comes out.
