### ISSUE TITLE
Wrong cert for environment causes background infinite loop with ClientNotConnectedException

### ISSUE THREAD

**Issue by dnatic09** [relayrides/pushy#279]
I just found a non-critical bug.  If you use the wrong cert against the wrong environment, you will get details in the logs that it is a "BadCertificateEnvironment".  This is completely expected given the improper configuration.  However, the recommended way of handling ClientNotConnectedException is to wait on the reconnect future to return.  BadCertificateEnvironment returns a ClientNotConnectedException thus causing an infinite background loop until a timeout occurs.  Despite having a 2 second connect and write timeout, this timeout always lasts 10 seconds.

Issue #1:  BadCertificateEnvironment should throw a different exception or a subclass of ClientNotConnectedException so the implementer can bypass the reconnect (and drop the message).

Issue #2:  This timeout behavior doesn't respect the client settings connect nor write timeouts.

Thanks!!!

Dan Natic

```
2016-04-25 12:35:03,519 INFO c.r.p.a.ApnsClient [nioEventLoopGroup-3-1] Connected to api.development.push.apple.com/17.110.227.100:443.
2016-04-25 12:35:03,583 INFO c.r.p.a.ApnsClientHandler [nioEventLoopGroup-3-1] Received GOAWAY from APNs server: {"reason":"BadCertificateEnvironment"}
2016-04-25 12:35:03,583 INFO c.r.p.a.ApnsClientHandler [nioEventLoopGroup-3-1] Received GOAWAY from APNs server:
2016-04-25 12:35:03,597 INFO c.w.d.s.DistributionServerStats$ [ForkJoinPool-2-worker-15] Ostrich [com.weather.distribution.stats.DistributionServerStats$]: Reporting stats
2016-04-25 12:35:09,028 INFO c.r.p.a.ApnsClient [nioEventLoopGroup-3-1] Connection to api.development.push.apple.com/17.110.227.100:443 restored.
2016-04-25 12:35:09,091 INFO c.r.p.a.ApnsClientHandler [nioEventLoopGroup-3-1] Received GOAWAY from APNs server: {"reason":"BadCertificateEnvironment"}
2016-04-25 12:35:09,092 INFO c.r.p.a.ApnsClientHandler [nioEventLoopGroup-3-1] Received GOAWAY from APNs server:
2016-04-25 12:35:19,409 ERROR c.w.d.d.a.ApnsHttp2PostActor [ActorManager-akka.actor.default-dispatcher-13] <* DC [Failed w/excpt] : Timed out after 10000 milliseconds (Chan=iphone-free, Prod=severe, UserIds=abc)
java.util.concurrent.TimeoutException: Timed out after 10000 milliseconds
	at scalaz.concurrent.Future$$anonfun$unsafePerformSyncAttemptFor$2.apply(Future.scala:225)
	at scalaz.concurrent.Future$$anonfun$unsafePerformSyncAttemptFor$2.apply(Future.scala:223)
	at scala.Option.getOrElse(Option.scala:120)
	at scalaz.concurrent.Future.unsafePerformSyncAttemptFor(Future.scala:223)
	at scalaz.concurrent.Task.unsafePerformSyncAttemptFor(Task.scala:202)
	at com.weather.distribution.distributor.apns.ApnsHttp2PostActor.sendDC(ApnsHttp2PostActor.scala:144)
	at com.weather.distribution.distributor.apns.ApnsHttp2PostActor$$anonfun$receive$1.applyOrElse(ApnsHttp2PostActor.scala:180)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at com.weather.distribution.distributor.apns.ApnsHttp2PostActor.aroundReceive(ApnsHttp2PostActor.scala:38)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-04-25 12:35:29,229 INFO c.r.p.a.ApnsClient [nioEventLoopGroup-3-1] Connection to api.development.push.apple.com/17.110.227.100:443 restored.
2016-04-25 12:35:30,738 INFO c.r.p.a.ApnsClientHandler [nioEventLoopGroup-3-1] Received GOAWAY from APNs server: {"reason":"BadCertificateEnvironment"}
2016-04-25 12:35:30,738 INFO c.r.p.a.ApnsClientHandler [nioEventLoopGroup-3-1] Received GOAWAY from APNs server:
2016-04-25 12:35:32,323 INFO c.r.p.a.ApnsClient [nioEventLoopGroup-3-1] Connection to api.development.push.apple.com/17.110.227.100:443 restored.
2016-04-25 12:35:33,510 WARN i.n.u.c.PromiseNotifier [nioEventLoopGroup-3-1] Failed to mark a promise as failure because it's done already: DefaultChannelPromise@711bf204(failure: java.io.IOException: Broken pipe)
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:524)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:305)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:859)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:311)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:826)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1436)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:351)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:351)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:505)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:351)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:351)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:161)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:351)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:401)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:272)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1186)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:286)
	at com.relayrides.pushy.apns.ApnsClient.sendNotification(ApnsClient.java:817)
	at com.weather.distribution.distributor.apns.ApnsHttp2Connection.send(ApnsHttp2PostActor.scala:234)
	at com.weather.distribution.distributor.apns.ApnsHttp2PostActor.sendNotif(ApnsHttp2PostActor.scala:100)
	at com.weather.distribution.distributor.apns.ApnsHttp2PostActor$$anonfun$sendNotif$1$$anonfun$applyOrElse$1.apply(ApnsHttp2PostActor.scala:101)
	at com.weather.distribution.distributor.apns.ApnsHttp2PostActor$$anonfun$sendNotif$1$$anonfun$applyOrElse$1.apply(ApnsHttp2PostActor.scala:101)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$.Try(Task.scala:446)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future.step(Future.scala:118)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:87)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:87)
	at scalaz.Free.resume(Free.scala:105)
	at scalaz.Free.go2$1(Free.scala:149)
	at scalaz.Free.go(Free.scala:153)
	at scalaz.Free.run(Free.scala:228)
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:429)
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:429)
	at com.weather.distribution.distributor.apns.ApnsHttp2Connection$$anonfun$nettyFuture2Task$1$$anonfun$apply$9$$anon$1.operationComplete(ApnsHttp2PostActor.scala:206)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:407)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at com.relayrides.pushy.apns.ApnsClient$3.operationComplete(ApnsClient.java:688)
	at com.relayrides.pushy.apns.ApnsClient$3.operationComplete(ApnsClient.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:407)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at com.relayrides.pushy.apns.ApnsClient$1$1$1.run(ApnsClient.java:447)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jchambers** [comment]
Hm. These aren't exceptions, per se. What's actually happening is that we're connecting successfully, but then the server is closing the connection immediately. It does seem like we could make a special case for this kind of thing, though we'll have to give some thought as to how to communicate the problem to callers.

**Comment by jchambers** [comment]
…also, I'm not sure what to make of the 10-second timeout. It's not clear to me what, exactly, is timing out or whether it's actually something in Pushy. Will take a look, though.

**Comment by jchambers** [comment]
I have two thoughts on this:

First, I think this may be impossible to resolve in a reasonable way since the connection *is* established successfully (i.e. we get a `SETTINGS` frame from the server), but is then closed some unknown amount of time later. We'd wind up in a situation where we'd have to report that the connection attempt succeed (because it did!), but then have some kind of wacky listener system to tell callers "just kidding; wrong certificate."

Second, I don't know that this is actually a huge problem worth solving. Apple now issues certificates that are good for both the development *and* production environments. If you use one of those, this problem should go away entirely. Also, this seeeems like the kind of thing that would only happen in development and isn't necessarily a case we need to be worried about (i.e. it won't spontaneously happen in long-running applications).

Does that make sense? I hate to take the lazy way out here, but I don't know that there's a non-lazy way that makes things better and not worse.

**Comment by dnatic09** [comment]
I was talking to my colleague, Thurston (whom you've spoken with on the mailing lists), and he agreed with you.  Something like this in production would probably never happen and therefore is not entirely worth fixing.  I agree.  We should just close this issue.

**Comment by jchambers** [comment]
Okay. We'll close this one for now, but will happily revisit if we learn that this is more of a problem than expected. Thanks for the report, and thanks for your consideration!
