### ISSUE TITLE
ApnsclientTest failed on NoClassDefFoundError: io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator

### ISSUE THREAD

**Issue by kennethkwng** [relayrides/pushy#297]
I went the Maven test specifying profile test-with-netty-tcnative on window platform using jdk1.8.0_65. The test failed on NoClassDefFoundError.

Here are Debug trace info from eclipse maven output. Am I missing anything. Please advise. Thanks

```
[DEBUG] Adding to surefire booter test classpath: C:\ken\.m2\repository\org\apache\maven\surefire\surefire-booter\2.16\surefire-booter-2.16.jar Scope: compile
[DEBUG] Adding to surefire booter test classpath: C:\ken\.m2\repository\org\apache\maven\surefire\surefire-api\2.16\surefire-api-2.16.jar Scope: compile
[DEBUG] Using JVM: C:\Program Files\Java\jdk1.8.0_65\jre\bin\java
[DEBUG] dummy:dummy:jar:1.0 (selected for null)
[DEBUG]   org.apache.maven.surefire:surefire-junit4:jar:2.16:test (selected for test)
[DEBUG]     org.apache.maven.surefire:surefire-api:jar:2.16:test (selected for test)
[DEBUG] Adding to surefire test classpath: C:\ken\.m2\repository\org\apache\maven\surefire\surefire-junit4\2.16\surefire-junit4-2.16.jar Scope: test
[DEBUG] Adding to surefire test classpath: C:\ken\.m2\repository\org\apache\maven\surefire\surefire-api\2.16\surefire-api-2.16.jar Scope: test
[DEBUG] test classpath:  C:\ken\workspaceUB\pushy\target\test-classes  C:\ken\workspaceUB\pushy\target\classes  C:\ken\.m2\repository\io\netty\netty-codec-http2\4.1.0.CR7\netty-codec-http2-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-codec-http\4.1.0.CR7\netty-codec-http-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-codec\4.1.0.CR7\netty-codec-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-handler\4.1.0.CR7\netty-handler-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-buffer\4.1.0.CR7\netty-buffer-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-common\4.1.0.CR7\netty-common-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-handler-proxy\4.1.0.CR7\netty-handler-proxy-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-transport\4.1.0.CR7\netty-transport-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-resolver\4.1.0.CR7\netty-resolver-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-codec-socks\4.1.0.CR7\netty-codec-socks-4.1.0.CR7.jar  C:\ken\.m2\repository\com\google\code\gson\gson\2.6.2\gson-2.6.2.jar  C:\ken\.m2\repository\org\slf4j\slf4j-api\1.7.6\slf4j-api-1.7.6.jar  C:\ken\.m2\repository\org\eclipse\jetty\alpn\alpn-api\1.1.2.v20150522\alpn-api-1.1.2.v20150522.jar  C:\ken\.m2\repository\junit\junit\4.11\junit-4.11.jar  C:\ken\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar  C:\ken\.m2\repository\org\slf4j\slf4j-simple\1.7.6\slf4j-simple-1.7.6.jar  C:\ken\.m2\repository\org\bouncycastle\bcpkix-jdk15on\1.53\bcpkix-jdk15on-1.53.jar  C:\ken\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.53\bcprov-jdk15on-1.53.jar  C:\ken\.m2\repository\io\netty\netty-tcnative-boringssl-static\1.1.33.Fork15\netty-tcnative-boringssl-static-1.1.33.Fork15-windows-x86_64.jar
[DEBUG] provider classpath:  C:\ken\.m2\repository\org\apache\maven\surefire\surefire-junit4\2.16\surefire-junit4-2.16.jar  C:\ken\.m2\repository\org\apache\maven\surefire\surefire-api\2.16\surefire-api-2.16.jar
[DEBUG] test(compact) classpath:  test-classes  classes  netty-codec-http2-4.1.0.CR7.jar  netty-codec-http-4.1.0.CR7.jar  netty-codec-4.1.0.CR7.jar  netty-handler-4.1.0.CR7.jar  netty-buffer-4.1.0.CR7.jar  netty-common-4.1.0.CR7.jar  netty-handler-proxy-4.1.0.CR7.jar  netty-transport-4.1.0.CR7.jar  netty-resolver-4.1.0.CR7.jar  netty-codec-socks-4.1.0.CR7.jar  gson-2.6.2.jar  slf4j-api-1.7.6.jar  alpn-api-1.1.2.v20150522.jar  junit-4.11.jar  hamcrest-core-1.3.jar  slf4j-simple-1.7.6.jar  bcpkix-jdk15on-1.53.jar  bcprov-jdk15on-1.53.jar  netty-tcnative-boringssl-static-1.1.33.Fork15-windows-x86_64.jar
[DEBUG] provider(compact) classpath:  surefire-junit4-2.16.jar  surefire-api-2.16.jar

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[DEBUG] boot classpath:  C:\ken\.m2\repository\org\apache\maven\surefire\surefire-booter\2.16\surefire-booter-2.16.jar  C:\ken\.m2\repository\org\apache\maven\surefire\surefire-api\2.16\surefire-api-2.16.jar  C:\ken\workspaceUB\pushy\target\test-classes  C:\ken\workspaceUB\pushy\target\classes  C:\ken\.m2\repository\io\netty\netty-codec-http2\4.1.0.CR7\netty-codec-http2-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-codec-http\4.1.0.CR7\netty-codec-http-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-codec\4.1.0.CR7\netty-codec-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-handler\4.1.0.CR7\netty-handler-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-buffer\4.1.0.CR7\netty-buffer-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-common\4.1.0.CR7\netty-common-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-handler-proxy\4.1.0.CR7\netty-handler-proxy-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-transport\4.1.0.CR7\netty-transport-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-resolver\4.1.0.CR7\netty-resolver-4.1.0.CR7.jar  C:\ken\.m2\repository\io\netty\netty-codec-socks\4.1.0.CR7\netty-codec-socks-4.1.0.CR7.jar  C:\ken\.m2\repository\com\google\code\gson\gson\2.6.2\gson-2.6.2.jar  C:\ken\.m2\repository\org\slf4j\slf4j-api\1.7.6\slf4j-api-1.7.6.jar  C:\ken\.m2\repository\org\eclipse\jetty\alpn\alpn-api\1.1.2.v20150522\alpn-api-1.1.2.v20150522.jar  C:\ken\.m2\repository\junit\junit\4.11\junit-4.11.jar  C:\ken\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar  C:\ken\.m2\repository\org\slf4j\slf4j-simple\1.7.6\slf4j-simple-1.7.6.jar  C:\ken\.m2\repository\org\bouncycastle\bcpkix-jdk15on\1.53\bcpkix-jdk15on-1.53.jar  C:\ken\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.53\bcprov-jdk15on-1.53.jar  C:\ken\.m2\repository\io\netty\netty-tcnative-boringssl-static\1.1.33.Fork15\netty-tcnative-boringssl-static-1.1.33.Fork15-windows-x86_64.jar  C:\ken\.m2\repository\org\apache\maven\surefire\surefire-junit4\2.16\surefire-junit4-2.16.jar
[DEBUG] boot(compact) classpath:  surefire-booter-2.16.jar  surefire-api-2.16.jar  test-classes  classes  netty-codec-http2-4.1.0.CR7.jar  netty-codec-http-4.1.0.CR7.jar  netty-codec-4.1.0.CR7.jar  netty-handler-4.1.0.CR7.jar  netty-buffer-4.1.0.CR7.jar  netty-common-4.1.0.CR7.jar  netty-handler-proxy-4.1.0.CR7.jar  netty-transport-4.1.0.CR7.jar  netty-resolver-4.1.0.CR7.jar  netty-codec-socks-4.1.0.CR7.jar  gson-2.6.2.jar  slf4j-api-1.7.6.jar  alpn-api-1.1.2.v20150522.jar  junit-4.11.jar  hamcrest-core-1.3.jar  slf4j-simple-1.7.6.jar  bcpkix-jdk15on-1.53.jar  bcprov-jdk15on-1.53.jar  netty-tcnative-boringssl-static-1.1.33.Fork15-windows-x86_64.jar  surefire-junit4-2.16.jar
Forking command line: cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_65\jre\bin\java" -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -jar C:\ken\workspaceUB\pushy\target\surefire\surefirebooter556594677626807144.jar C:\ken\workspaceUB\pushy\target\surefire\surefire6583644693904894418tmp C:\ken\workspaceUB\pushy\target\surefire\surefire_02642796118262937636tmp"
Running com.relayrides.pushy.apns.ApnsClientTest
Tests run: 64, Failures: 0, Errors: 64, Skipped: 0, Time elapsed: 5.839 sec <<< FAILURE! - in com.relayrides.pushy.apns.ApnsClientTest
testRejectedNotificationMetrics(com.relayrides.pushy.apns.ApnsClientTest)  Time elapsed: 2.149 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:27)
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24)
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:277)
	at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:226)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:405)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:391)
	at com.relayrides.pushy.apns.MockApnsServer.<init>(MockApnsServer.java:70)
	at com.relayrides.pushy.apns.ApnsClientTest.setUp(ApnsClientTest.java:220)
```

**Comment by jchambers** [comment]
Netty-tcnative had a host of Windows-related issues. I believe they've been fixed in [fork17](https://github.com/netty/netty-tcnative/issues?q=milestone%3A1.1.33.Fork17+is%3Aclosed), which we use for tests as of cbc2404.

**Comment by kennethkwng** [comment]
Is fork17 available in mvn repo?

**Comment by jchambers** [comment]
[Yes](http://search.maven.org/#artifactdetails%7Cio.netty%7Cnetty-tcnative-boringssl-static%7C1.1.33.Fork17%7Cjar).

**Comment by jchambers** [comment]
It does sound like there's an issue with the native libraries in fork16/fork17: https://github.com/netty/netty-tcnative/issues/145

Given the issues, I'm not entirely sure how/why it's working for us (all of our tests pass with fork17 and no classifier, for instance). Let's keep an eye on the issue and see how things develop; in the meantime, you may be better served by doing things the "old-fashioned" way by specifying an OS classifier.

Sound good?
