### ISSUE TITLE
OpenSSL (via netty-tcnative) not available

### ISSUE THREAD

**Issue by pad90** [relayrides/pushy#303]
I am trying to run the exampleApp.java in my project and got the following error, thanks in advance:

```
Mai 30, 2016 1:55:55 PM com.relayrides.pushy.apns.ApnsClient getBaseSslContextBuilder
INFO: OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:26)
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24)
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:285)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:261)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:742)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:395)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:392)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:386)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:363)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:264)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:238)
	at ch.bdna.ruletest.ExampleApp.main(ExampleApp.java:32)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

I tried the debug from this post: https://github.com/netty/netty/issues/5052

and the output:

```
OpenSSL available? false
ALPN available?    false
Unavailability cause:
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-windows-x86_64, netty-tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:167)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:78)
	at ch.bdna.ruletest.test.main(test.java:8)
```

**Comment by jchambers** [comment]
Hi! This sounds like more of a request for general support than it sounds like a bug report or feature request. We'd be happy to help, but it's probably better to move this conversation to [the mailing list](https://groups.google.com/d/forum/pushy-apns) for a few reasons:

1. The mailing list has a wider audience of people who might be able to contribute to an answer.
2. The wider audience on the mailing list could also benefit from a more public conversation; this sounds like the kind of thing that would be of general interest to the Pushy community.
3. We can't reasonably resolve this issue by committing code.

Sound good?

In the meantime, I can tell you that this is expected behavior if you haven't followed the instructions in the [System Requirements section of the README](https://github.com/relayrides/pushy#system-requirements). You'll need to either add `netty-tcnative` to your classpath or add a specific version of Jetty's `alpn-boot` package to your *boot* classpath, which I emphasize is different from your normal classpath.

I'll close this issue for now, but please ask on the mailing list if you have further questions.
