### ISSUE TITLE
Infinite reconnection retries using an expired certificate

### ISSUE THREAD

**Issue by conet** [relayrides/pushy#304]
I really like the way pushy provides connection persistency with APNS using automatic reconnects.

But, as far as I can see, there is a problem with this feature. Our push notifications delivery service maintains a set of APNS clients connected over a long period of time to be able to deliver notifications instantly. In the following case the APNS client attempts to reconnect indefinitely and there is no way to subscribe to the reconnect event while the connection is successful and no notifications are sent:

1. The connection was successful while the certificate was valid
2. In the meantime the certificate expired and the APNS disconnected the client
3. The client connects indefinitely until disconnect() is called and the log is filled with the following error

```
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:219)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:82)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:970)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)
```

Wouldn't it be better to provide a way to subscribe to a reconnect event even if connected (which would not succeed immediately like it does now) and let the client decide if reconnection should go ahead or better yet don't try to reconnect when it's certain that subsequent request will not work like in the above case.

Currently if one maintains a set of APNS clients there is no way around this but to periodically check each client's isConnected() attribute.

Thanks for developing this awesome library.

**Comment by jchambers** [comment]
> Wouldn't it be better to provide a way to subscribe to a reconnect event even if connected…

I definitely see where you're going, and this is actually what we used to do in the pre-HTTP/2 days. Now that reconnection is much less frequent, though, I'm worried that exposing reconnection listeners would introduce a lot of complexity/generality for for a pretty specific problem.

One thing we learned about reconnection listeners is that, when you're just looking at an exception, it's hard to tell the difference between an expired certificate and some other transient problem. To check for expired certificates specifically, it seems like callers could achieve the same thing more reliably by keeping track of [`X509Certificate#getNotAfter()`](https://docs.oracle.com/javase/7/docs/api/java/security/cert/X509Certificate.html#getNotAfter()). Would that work in your case? If not, why?

**Comment by conet** [comment]
You are right that would be better and would work, but it would cover only the cases when the certificate expires. Certificates might stop working because they are removed from the developer account. I think I'll stick to checking isConnected() periodically for all clients and disconnecting the ones that don't seem to able to reconnect.

**Comment by jchambers** [comment]
> Certificates might stop working because they are removed from the developer account.

That's a good point, and not a case I'd really been thinking about.

> I think I'll stick to checking isConnected() periodically for all clients and disconnecting the ones that don't seem to able to reconnect.

That seems a little risky, since there may be false positives due to normal reconnection. If you have a monitoring platform you like, how about using an [`ApnsClientMetricsListener`](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/ApnsClientMetricsListener.html) instead? You could look for an unusual increase in the number of connection attempts and set alarms accordingly. Does that seem reasonable?

**Comment by conet** [comment]
> That seems a little risky, since there may be false positives due to normal reconnection. If you have a monitoring platform you like, how about using an ApnsClientMetricsListener instead? You could look for an unusual increase in the number of connection attempts and set alarms accordingly. Does that seem reasonable?

Thanks, I haven't thought of that, this solution sounds much better and I think I'll used it since I do have a monitoring platform. It provides just the information that I thought was missing so I'm going to close the issue.

**Comment by jchambers** [comment]
Cool! Glad to hear that will work for you, and thanks for all your patience in exploring the options!
