### ISSUE TITLE
NPE on P12Util.getPrivateKeyEntryFromP12InputStream

### ISSUE THREAD

**Issue by ScienJus** [relayrides/pushy#306]
```
Exception in thread "main" java.lang.NullPointerException: invalid null input
	at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:524)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetEntry(PKCS12KeyStore.java:1287)
	at java.security.KeyStore.getEntry(KeyStore.java:1521)
	at com.relayrides.pushy.apns.P12Util.getPrivateKeyEntryFromP12InputStream(P12Util.java:33)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:372)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:363)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:264)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:238)
```

Mac OS X 10.11.4 and JDK 1.8

is something wrong with SSL?

**Comment by ScienJus** [comment]
i used wrong p12 file, sorry
