### ISSUE TITLE
java.lang.NoSuchFieldError: EXT_ALPN

### ISSUE THREAD

**Issue by carlosDialcom** [relayrides/pushy#338]
I am triying to run Pushy on windows with tomcat 8 and Oracle 1.8 with Jetty's ALPN implementation. It gives me a very rare error and I can not find information about it. I have spend several days but nothing works.

When i try to init Pushy my console ouput is:

```
java.lang.NoSuchFieldError: EXT_ALPN
	at sun.security.ssl.ALPNExtension.<clinit>(ALPNExtension.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.netty.handler.ssl.JdkAlpnSslEngine.updateAvailability(JdkAlpnSslEngine.java:48)
	at io.netty.handler.ssl.JdkAlpnSslEngine.isAvailable(JdkAlpnSslEngine.java:37)
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:26)
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24)
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:285)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:261)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:742)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:395)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:394)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:388)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:365)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:266)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:239)
	at com.dialcom.pushserver.providers.ApplePushHttp2Provider.configPushyLibrary(ApplePushHttp2Provider.java:98)
	at com.dialcom.pushserver.providers.ApplePushHttp2Provider.setPushProviderConfig(ApplePushHttp2Provider.java:93)
	at com.dialcom.pushserver.Manager.init(Manager.java:79)
	at com.dialcom.pushserver.PushServerContextListener.contextInitialized(PushServerContextListener.java:29)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Thanks in advance

**Comment by jchambers** [comment]
How, exactly, are you using Jetty's ALPN implementation? Are you adding `alpn-boot` to your boot classpath manually, or are you using something like `alpn-agent`? It sounds to me like you may have a version mismatch between `alpn-boot` and your JDK.

**Comment by carlosDialcom** [comment]
I am adding alp-boot to boot classpath manually. I am trying different versions of alpn-boot but nothing works. My  java version is Oracle 1.8u66 in this case my alp-boot version should be 8.1.6.v20151105 according to http://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html. I am using Oracle JVM but this website always says about Open JDK versions. Is it  important in this case?

Thanks for your fast answer :)

**Comment by jchambers** [comment]
For Science™, would you mind trying [`alpn-agent`](https://github.com/jetty-project/jetty-alpn-agent) instead of going directly for `alpn-boot`?

**Comment by jchambers** [comment]
One other thought: are you using a non-standard crypto provider?

**Comment by jchambers** [comment]
@carlosDialcom I'm going to close this for now due to a lack of activity. It sounds like nobody else is having this problem, and I can't reproduce it. Please do leave a comment here if you get a chance to investigate further and we'll happily re-open the issue. Thanks!
