### ISSUE TITLE
Performance decrease suddenly 

### ISSUE THREAD

**Issue by sorheart** [relayrides/pushy#346]
How there.
I'm facing a very strange problem,  the performance can decrease very suddenly and obviously.
First I can send about 5k notifications in a second, but it drops quickly.After several minutes, i can only send about 100 notification in a second.

To clarify, 5k is the number that successfully send to the server, I counted each time I received a 200 status response.

**Comment by sorheart** [comment]
Checked the log, I find a lot of exceptions like:
[WARN] io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:520): An exception was thrown by com.htsc.iospushy.PushyClient$1.operationComplete()
        ... 8 more
Caused by: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.

**Comment by sorheart** [comment]
The full log is
2016-07-25 17:29:40,058 [WARN] io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:520): An exception was thrown by com.htsc.iospushy.PushyClient$1.operationComplete()
        ... 8 more
Caused by: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.
        at java.lang.Thread.run(Thread.java:745)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at com.relayrides.pushy.apns.ApnsClient$2$2.run(ApnsClient.java:743)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:431)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:518)

**Comment by sorheart** [comment]
And there is another exception:
2016-07-25 09:40:48,501 [WARN] io.netty.util.concurrent.PromiseNotifier.operationComplete(PromiseNotifier.java:70): Failed to mark a promise as failure because it's done already: DefaultChannelPromise@29b66880(failure: java.n
io.channels.ClosedChannelException)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryFailure(Http2CodecUtil.java:258)
        at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:689)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)

**Comment by jchambers** [comment]
Some questions to help narrow down what's happening here:

1. Are you using the production environment or the development environment?
2. How long does it take to fall back from ~5k notifications/second?
3. Do you see connection closures even if you're not sending notifications (i.e. if you just open a connection and watch it for a minute, what happens)?
4. Do you see any lines in your logs that report a `GOAWAY` frame from the server? We're looking for this line, in particular: https://github.com/relayrides/pushy/blob/v0.7.3/pushy/src/main/java/com/relayrides/pushy/apns/ApnsClientHandler.java#L223

Thanks!

**Comment by sorheart** [comment]
1 I'm using the production environment.
2 about 1 or 2 minute
3 I didn't see any closure, it seems only happens when i'm sending notifications.
4 I have not found anything like that.

more details:
I'm using a apnsclient pool, and all of them share one eventLoopGroup.
I do find connection lost in the log, but the strange thing is I cannot find the GOAWAY mark.

**Comment by sorheart** [comment]
OK, I find that I didn't use sf4j-log4j, so pushy won't print any log.
I'll republish my code and see if there is any GOAWAY mark.

**Comment by sorheart** [comment]
Ok, there is what i've found in the last days:
The connection may close at any time, and when it does, I get the log like:
2016-07-28 12:25:58,543 [WARN] io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:146): An exception was thrown by com.htsc.iospushy.PushyClient$1.operationComplete()
        ... 8 more
Caused by: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.
        at java.lang.Thread.run(Thread.java:745)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at com.relayrides.pushy.apns.ApnsClient$2$2.run(ApnsClient.java:1091)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:431)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:518)
        at com.htsc.iospushy.PushyClient$1.operationComplete(PushyClient.java:80)
        at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
java.util.concurrent.ExecutionException: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.

The strange thing is there is no GOAWAY mark, looks like the connection lost for no reason.

**Comment by jchambers** [comment]
@sorheart That's extremely strange. At the risk of being needy, what's your slf4j log level right now? What happens if you set it to `DEBUG` or even `TRACE`?

**Comment by jchambers** [comment]
And one more maybe-dumb question: are you sure you're waiting for the connection future to complete before you start trying to send notifications?

**Comment by sorheart** [comment]
All right, after days of searching and  analysing, 
it looks to me that some of the apns server works good, but some of them works bad and occasionally break off the connection. Like the following discussion:
https://forums.developer.apple.com/thread/44866

I think it's an apple problem, not pushy's problem.

**Comment by jchambers** [comment]
Bummer. I'll see if I can raise awareness for the issue. Thanks for digging into it!

**Comment by jchambers** [comment]
Actually, @sorheart, have you filed a [bug report](https://bugreport.apple.com/) with Apple yet?

**Comment by sorheart** [comment]
Not yet. I'm still gathing information by setting log level to DEBUG.
Will update when finding something useful.

**Comment by jchambers** [comment]
Thank you!

**Comment by xiaohuishu** [comment]
@sorheart  will this issue conclusions yet
