### ISSUE TITLE
APNs client pipeline caught an exception

### ISSUE THREAD

**Issue by kkrgwbj** [relayrides/pushy#365]
Hi @jchambers , thank you do this project. We have also been using this project, yesterday i am happy to see to see the project to upgrade the 0.8, I soon will be upgrading my project to 0.8. However, today met a strange question. Project running for some time, there will be the exception. I opened three tomcat nodes, but only one experiencing this problem, reconnection reconnection mechanism sometimes fail. hope to get your feedback.
Error message:

```
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@28a2b3d9(incomplete)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:398) ~[netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157) ~[netty-transport-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:233) ~[netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129) ~[netty-transport-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:233) ~[netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129) ~[netty-transport-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28) ~[netty-transport-4.1.4.Final.jar:4.1.4.Final]
    at com.xwtec.listener.PushFutureListener.operationComplete(PushFutureListener.java:76) ~[PushFutureListener.class:?]
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at com.relayrides.pushy.apns.ApnsClient$2$2.run(ApnsClient.java:443) [pushy-0.8.jar:?]
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401) [netty-transport-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
java.util.concurrent.ExecutionException: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.
    at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
    at com.xwtec.listener.PushFutureListener.operationComplete(PushFutureListener.java:32)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
    at com.relayrides.pushy.apns.ApnsClient$2$2.run(ApnsClient.java:443)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
    at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
```

**Comment by jchambers** [comment]
Sounds like you may just have a connection to a flaky server upstream on that one node. This all seems completely normal to me, though (assuming that the connection closed unexpectedly). Do you have reason to believe that there's something going wrong in Pushy itself?

**Comment by Ossic** [comment]
@kkrgwbj hi, have you solve the exception BlockingOperationException, I met the same problem.

**Comment by jchambers** [comment]
@Ossic Please upgrade to the latest version of Pushy, which has long since solved this problem.

**Comment by Ossic** [comment]
@jchambers It works.
So thanks.
