### ISSUE TITLE
Pushy on Alpine Docker Container ALPN problems

### ISSUE THREAD

**Issue by artefactop** [relayrides/pushy#366]
Hello,

I'm trying to run my service inside a docker container and I get problems with ALPN
```java
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:26)
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24)
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:285)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:261)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:742)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:395)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:394)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:388)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:365)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:266)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:239)
	at com.wallapop.pushsender.configuration.apns.APNSConfiguration.lambda$buildAndConnect$2(APNSConfiguration.java:56)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at com.wallapop.pushsender.configuration.apns.APNSConfiguration.buildAndConnect(APNSConfiguration.java:54)
	at com.wallapop.pushsender.configuration.apns.LocalConfiguration.apnsClients(LocalConfiguration.java:51)
	at com.wallapop.pushsender.configuration.apns.LocalConfiguration$$EnhancerBySpringCGLIB$$57a99435.CGLIB$apnsClients$0(<generated>)
	at com.wallapop.pushsender.configuration.apns.LocalConfiguration$$EnhancerBySpringCGLIB$$57a99435$$FastClassBySpringCGLIB$$e34a90fb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at com.wallapop.pushsender.configuration.apns.LocalConfiguration$$EnhancerBySpringCGLIB$$57a99435.apnsClients(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more
```

I'm using alpine as operative system version `Linux 1a335bcfac0f 4.4.19-moby #1 SMP Mon Aug 22 23:30:19 UTC 2016 x86_64 Linux` with java `openjdk version "1.8.0_92-internal"`

I had no problems on my mac or other linux machine and I'm not able to resolve it
My dependencies are `com.relayrides:pushy:0.7.3` and `io.netty:netty-tcnative-boringssl-static:1.1.33.Fork21`

Any thoughts?

**Comment by artefactop** [comment]
I found the problem, netty-tcnative is not compiled for alpine linux see this issue https://github.com/netty/netty-tcnative/issues/111 I changed base image to debian
