### ISSUE TITLE
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed

### ISSUE THREAD

**Issue by starikoff** [relayrides/pushy#384]
I have a problem when connecting to APNS (using pushy version 0.7.3):

```
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
 at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:712)
 at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:704)
 at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:518)
 at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:492)
 at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:431)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
 at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:108)
 at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
 at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1049)
 at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:674)
 at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:652)
 at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:596)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1256)
 at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:610)
 at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:594)
 at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
 at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:610)
 at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:594)
 at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1250)
 at io.netty.handler.ssl.SslHandler.close(SslHandler.java:459)
 at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:610)
 at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:594)
 at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:451)
 at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:943)
 at io.netty.channel.AbstractChannel.close(AbstractChannel.java:227)
 at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:56)
 at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:52)
 at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:518)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:511)
 at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:490)
 at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:431)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
 at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
 at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:325)
 at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:580)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
 at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
 at java.lang.Thread.run(Thread.java:745)
```

The code, when stripped off of my constants, is

            apnsClient = new ApnsClient<>(
                    MyApnsClient.class.getResourceAsStream("MyCertificate.p12"),
                    "password");
            Future<Void> connectFuture = apnsClient.connect(
                    ApnsClient.DEVELOPMENT_APNS_HOST,
                    ApnsClient.DEFAULT_APNS_PORT);
            connectFuture.get(10_000, TimeUnit.MILLISECONDS); // here the exception happens

It worked fine on several different hosts previously (development, staging). The problem happened on the production host on the first deploy.

Are there any workarounds possible? Should I try connecting several times? Should I wait longer? This happened in the environment that I don't control, so I'll have to account for such situations in the code... Deployers refused to proceed further until I do something about it and claim the problem to be resolved (:

If more information is necessary, I'll be happy to provide it.
Thank you.

**Comment by jchambers** [comment]
If you set your log level to `DEBUG`, there should be some more information around the exception that provides more context. Without more information, all we know is that the connection closed, but don't know why.

**Comment by starikoff** [comment]
Hello Jon.
Thank you for your fast response.

From the error message I didn't understand it was just a "could not connect", though having looked into the source code (after creating this issue — my bad) I got that, and your comment certainly reassured me.

Ironically, after I'd set the log level to DEBUG and "retried" (which sounds a lot simpler than it is with our prod restrictions, that's why I thus far have only 2 data points: 1 failure, 1 success), the problem did not reproduce: the client connected to the APNS successfully.

Will keep an eye on the way it goes, but not knowing when/if the situation will happen next time, I'm closing the issue (right?). Perhaps I will implement some sort of retrying for connecting initially anyway.

Overall -- sorry for disturbing, and thank you.

**Comment by agyorev** [comment]
I'm experiencing the same issue, and no matter if I retry or change the logging level I'm consistently getting `java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed` every time.
```
com.relayrides.pushy.apns.ApnsClient$3 operationComplete: Failed to connect.
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:712)
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:704)
...
```

**Comment by jchambers** [comment]
@agyorev Is there any more context in the logs at finer (i.e. `DBEUG`) log levels? Can you tell us more about how you've confirmed that your certificates are valid and working?

**Comment by agyorev** [comment]
@jchambers thanks for the quick response!

So this is another thing that popped up in the logs:
```
io.netty.util.internal.logging.Slf4JLogger warn: Failed to initialize a channel. Closing: [id: 0x3c39d631]
java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.ssl.OpenSslEngine
	at io.netty.handler.ssl.OpenSslContext.newEngine(OpenSslContext.java:339)
	at io.netty.handler.ssl.OpenSslContext.newEngine(OpenSslContext.java:349)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:842)
	at com.relayrides.pushy.apns.ApnsClient$1.initChannel(ApnsClient.java:452)
	at com.relayrides.pushy.apns.ApnsClient$1.initChannel(ApnsClient.java:436)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:141)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:120)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1293)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:141)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:127)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:799)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:498)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:412)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:471)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

I used another APNS push service library (notnoop) to send a push with my certs and it was delivered successfully.

**Comment by jchambers** [comment]
@agyorev Sounds like there's some kind of version mismatch between Netty and whichever version of `netty-tcnative` you're trying to use. Are you using either (a) Windows or (b) Tomcat?

**Comment by agyorev** [comment]
@jchambers Nope, Jetty.

**Comment by Jagkalai10** [comment]
I encounter the same issue after migrating to Azure kubernetes service. The certificate is valid with apple.com outbound firewall is opened. Do we have any resolution to this?
