### ISSUE TITLE
NoClassDefFoundError ApnsPushNotification Class

### ISSUE THREAD

**Issue by marian09** [relayrides/pushy#418]
Hi, I have this problem:

```
Exception in thread "ActiveMQ Session Task-1" java.lang.NoClassDefFoundError: com/relayrides/pushy/apns/ApnsPushNotification
Caused by: java.lang.ClassNotFoundException: com.relayrides.pushy.apns.ApnsPushNotification
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1295)
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1147)
... 10 more
```

I have added this one like a maven dependency on my project.
Thanks.

**Comment by jchambers** [comment]
I see that you've moved this question to the mailing list; this appears to be more of a general support question than a bug report, so I'll close this issue and do my best to help you on the mailing list.

**Comment by marian09** [comment]
Thanks, I created a new question on the maining list y think
https://groups.google.com/forum/#!topic/pushy-apns/CWvgNPp9yqk

I hope you can help me and thank you so much really :)

2017-01-26 17:21 GMT-04:00 Jon Chambers <notifications@github.com>:
