### ISSUE TITLE
Force-closing a channel whose registration task was not accepted by an event loop

### ISSUE THREAD

**Issue by kadar2012** [relayrides/pushy#429]
my pushy version is 0.9.1, jdk 1.8 ,netty 4.1.8.Final,
i am getting below issue, i can only able to send 2028 count of successful IOS push notification. after that i am getting below error,
using alpn-boot-8.1.10.v20161026-2.jar i am running this in local.

**Code i connect for apnsClient and send push notification:**

```java
//keystore - is .p12 cert file
ApnsClient apnsClient = new ApnsClientBuilder().setClientCredentials(new File(keystore), password).build();
io.netty.util.concurrent.Future<Void> connectFuture = apnsClient.connect(ApnsClient.PRODUCTION_APNS_HOST);
connectFuture.await();

SimpleApnsPushNotification pushNotification;
ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
payloadBuilder.setAlertBody(tokenMsg[1]);
String payload = payloadBuilder.buildWithDefaultMaximumLength();
String token = TokenUtil.sanitizeTokenString((String) object);
pushNotification = new SimpleApnsPushNotification(token, “com.push.testprod”, payload);

io.netty.util.concurrent.Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = apnsClient
		.sendNotification(pushNotification);
```

**Error Log,**

```
[23 Feb 2017 17:29:42]  WARN  io.netty.channel.AbstractChannel                   - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x00afe7a9]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:33)
	at io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:847)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:840)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:745)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:475)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:126)
	at com.relayrides.pushy.apns.ApnsClient.connect(ApnsClient.java:457)
	at com.relayrides.pushy.apns.ApnsClient.connect(ApnsClient.java:418)
	at sg.gov.hdb.pushy.BF08PushUnsubPayload.send(BF08PushUnsubPayload.java:135)
	at sg.gov.hdb.pushy.BF08PushUnsubPayload.main(BF08PushUnsubPayload.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
```

**Comment by jchambers** [comment]
This seems to be the telling bit:

> `java.lang.OutOfMemoryError: unable to create new native thread`

Two questions:

1. Are you creating a new `ApnsClient` every time you send a notification?
2. When (and how) are you shutting down your `ApnsClients`?

**Comment by kadar2012** [comment]
Hi jchambers, 
1. yes i am creating apnsClient every time i send push notification
2. i am not shutting down apnsClient.

**Comment by jchambers** [comment]
Well, that's your problem, then. From the [`ApnsClient` docs](http://relayrides.github.io/pushy/apidocs/0.9/com/relayrides/pushy/apns/ApnsClient.html):

> APNs clients are intended to be long-lived, persistent resources. Callers should shut them down when they are no longer needed (i.e. when shutting down the entire application).

Every time you create a new `ApnsClient`, that client creates its own "event loop" thread (unless you pass it a specific `EventLoopGroup`, which you're not). That means that you're creating ~2,000 threads, each with its own stack, and then your JVM runs out of memory (which is exactly what we'd expect). There's no bug here; you just need to reuse a single `ApnsClient`, clean up unused clients, or both.

**Comment by kadar2012** [comment]
oops! thanks you so much will try it out. one more request. 

when is the prefer to shutdown apnsClient.

**Comment by kadar2012** [comment]
oops thanks! will try it out.

**Comment by kadar2012** [comment]
@jchambers thanks for the quick guidance. now i can send push notification with no issues.

how long it will take approx to send 1,00,000 push notification in general.
