### ISSUE TITLE
Push stuck the thread on WAITING state

### ISSUE THREAD

**Issue by shaymolho** [relayrides/pushy#432]
Hi, 

I'm new to this library.
We just started using it on our Production system few days ago, and i got to a situation which it stucked the running thread for eternal while calling "get" on the future object.

This is the thread stacktrace:

```
"pool-42-thread-1" #39 prio=5 os_prio=0 tid=0x00007fc27cfe2000 nid=0x6715 in Object.wait() [0x00007fc2802cd000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:239)
        - locked <0x00000006df89ad18> (a io.netty.util.concurrent.DefaultPromise)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:34)
        at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
        at com.socia.application.pushnotifications.PushNotificationsIosSenderServiceImpl$1.executeBulk(PushNotificationsIosSenderServiceImpl.java:133)
        at com.socia.common.utils.collection.CollectionsBulkUtil.executeInBulk(CollectionsBulkUtil.java:15)
        at com.socia.application.pushnotifications.PushNotificationsIosSenderServiceImpl.pushNotificationsToDevices(PushNotificationsIosSenderServiceImpl.java:110)
        at com.socia.application.pushnotifications.PushNotificationsBroadcastServiceImpl.broadcastNotificationToUsersImpl(PushNotificationsBroadcastServiceImpl.java:179)
        at com.socia.application.pushnotifications.PushNotificationsBroadcastServiceImpl.broadcastNotificationToUsers(PushNotificationsBroadcastServiceImpl.java:120)

```

And this is the relevant code snippet.
Notice that i'm calling to sendNotification multiple times and than executing get on all the Future objects.

```java
List<Pair<Future<PushNotificationResponse<SimpleApnsPushNotification>>, Long>> 
futuresAndDeviceIds = new ArrayList<>();

for (DeviceItem device : devices) {
    Long deviceId = device.getId();
    String pushToken = TokenUtil.sanitizeTokenString(device.getPushToken());

    SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(pushToken, topic, payload);

    Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = apnsClient.sendNotification(pushNotification);
    futuresAndDeviceIds.add(Pair.create(sendNotificationFuture, deviceId));
}

for (Pair<Future<PushNotificationResponse<SimpleApnsPushNotification>>, Long> futuresAndDeviceId : futuresAndDeviceIds) {
    Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = futuresAndDeviceId.getFirst();
    Long deviceId = futuresAndDeviceId.getSecond();


    try {
        final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse = sendNotificationFuture.get();
        if (pushNotificationResponse.isAccepted()) {
            succeedDeviceIds.add(deviceId);
        } else {
            failedDeviceIds.add(deviceId);
        }
    } catch (ExecutionException e) {
        // Something went wrong when trying to send the notification to the APNs gateway. The notification never actually reached the gateway, so we shouldn't consider this a permanent failure.
        failedDeviceIds.add(deviceId);

        LOG.error("Failed to send push notification", e);

        if (e.getCause() instanceof ClientNotConnectedException) {
            // If we failed to send the notification because the client isn't connected, we can wait for an automatic reconnection attempt to succeed before sending more notifications.
            try {
                apnsClient.getReconnectionFuture().await();
            } catch (Exception e1) {
                String msg = "Failed to Reconnect";
                LOG.error(msg, e1);
                throw new RuntimeException(msg, e1);
            }
        }
    } catch (Exception ex) {
        String msg = "Failed to send push notification on Unexpected Error, Stopping Batch";
        throw new RuntimeException(msg, ex);
    }
}
```

Is there a bug, or something that I do wrong?

Shay

**Comment by jchambers** [comment]
> Is there a bug, or something that I do wrong?

A little bit of both, and a little bit of neither ;)

In principle, what you've written *should* work. In reality, though, we might run into situations where network oddities prevent the server from responding in a timely manner, in which case what you've written will block indefinitely. There are two broad approaches you could take to solve the problem.

First, you could use listeners instead of calling `.get` on the `Future`. That's generally non-blocking, but won't fundamentally resolve the "some notifications seem to hang forever" problem.

Second, you could [set a write timeout](http://relayrides.github.io/pushy/apidocs/0.9/com/relayrides/pushy/apns/ApnsClientBuilder.html#setWriteTimeout-long-java.util.concurrent.TimeUnit-) so notifications don't get stuck in the "pipe" forever. Note that this won't address cases where we successfully send a notification, but the APNs server explodes and never replies.

Between the two approaches, I think you'll find that your problem is largely solved; I don't think there's a bug here, per se, but please do let us know if that doesn't resolve the problem and we'll see if something larger might be amiss.

**Comment by jchambers** [comment]
Closing for now, since I'm pretty sure this isn't a bug. @shaymolho if you feel otherwise, please comment here and we'll happily reopen the issue. Cheers!
