### ISSUE TITLE
ApnsClient.connect NPE

### ISSUE THREAD

**Issue by fruitJazzy** [relayrides/pushy#438]
When i try to connect i get NPE.

```
final ApnsClient apnsClient = new ApnsClientBuilder()
                .setClientCredentials(new File("cert.p12"), "pass")
                .build();
        final Future<Void> connectFuture = apnsClient.connect(ApnsClient.PRODUCTION_APNS_HOST);
```

> 11:21:17.138 [main] INFO  c.r.pushy.apns.ApnsClientBuilder - Native SSL provider is available and supports ALPN; will use native provider.
Exception in thread "main" java.lang.NullPointerException

Used Pushy 0.9.2 with netty-tcnative 2.0.0.Final windows-x86_64

**Comment by jchambers** [comment]
Can you provide a more complete stack trace? I suspect the problem may be that something changed in the latest version of `netty-tcnative`. What happens if you try `netty-tcnative-parent-1.1.33.Fork26`?

**Comment by fruitJazzy** [comment]
On 2.0 its all stack trace.

Change to 1.1.33.fork26
And i get 

> 16:21:08.687 [main] INFO  c.r.pushy.apns.ApnsClientBuilder - Native SSL provider not available; will use JDK SSL provider.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:285)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:261)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:751)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:418)
	at com.relayrides.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:430)
	at ru.i_dgtl.messaging.connectors.pushka.A.main(A.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: ALPN unsupported. Is your classpatch configured correctly? See http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:27)
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24)
	... 11 more

**Comment by fruitJazzy** [comment]
solved 
added 
`  <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>4.1.9.Final</version>
        </dependency>` and change back to 2.0.0

**Comment by kartikla** [comment]
how did you solve this problem ? I also get this message  
Native SSL provider not available; will use JDK SSL provider
