### ISSUE TITLE
java.util.concurrent.ExecutionException: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.

### ISSUE THREAD

**Issue by zhouxiaohai** [relayrides/pushy#457]
```
java.util.concurrent.ExecutionException: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
	at com.ejiahe.eim.push.reference.apns.source.PushyManager$1.operationComplete(PushyManager.java:150)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at com.relayrides.pushy.apns.ApnsClient$3$2.run(ApnsClient.java:514)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by zhouxiaohai** [comment]
hi:
    Always throw this exception!

**Comment by jchambers** [comment]
To be blunt, this is not enough information to effectively guess what's going wrong in your case. Can you please explain when this happens? Are you certain you're actually connecting your client before trying to send push notifications? Is it possible that you're [shutting down your connection too early](https://github.com/relayrides/pushy/wiki/Frequently-asked-questions#i-sent-a-bunch-of-notifications-and-lots-but-not-all-of-them-failed-with-an-http2goawayexception-or-clientnotconnectedexception-how-come)?

In any case, it seems unlikely that this is a bug with Pushy itself, and so I'm going to close this issue until we learn otherwise. Please feel free to provide additional information here and we'll reopen the issue if necessary.

Thanks!
