### ISSUE TITLE
io.netty.handler.codec.http2.StreamBufferingEncoder$Http2GoAwayException

### ISSUE THREAD

**Issue by qiankunli** [relayrides/pushy#472]
my pushy version is v0.10 and jdk version 1.8.0_65

there is a lot of StreamBufferingEncoder$Http2GoAwayException，the server is located in china ,so that the quality of connection with apple push server is not good.

the detail is:

	2017-06-03 07:16:05:WARN nioEventLoopGroup-2-5 com.ximalaya.pns.apple.listener.SingleFutureListener -
	io.netty.handler.codec.http2.StreamBufferingEncoder$Http2GoAwayException
		at io.netty.handler.codec.http2.StreamBufferingEncoder.cancelGoAwayStreams(StreamBufferingEncoder.java:253)
		at io.netty.handler.codec.http2.StreamBufferingEncoder.access$000(StreamBufferingEncoder.java:59)
		at io.netty.handler.codec.http2.StreamBufferingEncoder$1.onGoAwayReceived(StreamBufferingEncoder.java:121)
		at io.netty.handler.codec.http2.DefaultHttp2Connection.goAwayReceived(DefaultHttp2Connection.java:232)
		at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.onGoAwayRead0(DefaultHttp2ConnectionDecoder.java:164)
		at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onGoAwayRead(DefaultHttp2ConnectionDecoder.java:484)
		at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readGoAwayFrame(DefaultHttp2FrameReader.java:592)
		at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:272)
		at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)

**Comment by jchambers** [comment]
I think this is Just A Thing That Happens In China™, which is a real bummer. Please see #433, though; at least some users have found a viable workaround for this situation. That said, I don't think I've seen this stack trace before; when and where are you getting this exception? Is this the `cause()` for a failed future?

**Comment by qiankunli** [comment]
public void doOperationComplete(Future<PushNotificationResponse<SimpleApnsPushNotification>> future) throws InterruptedException, java.util.concurrent.ExecutionException {
        if (future.isSuccess()) {
            try {
                PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse =
                        future.get(1, TimeUnit.SECONDS);
                onFutureSuccess(notificationCompositeParam, pushNotificationResponse);
            }catch (Exception e){
                notificationCompositeParam.logFail(PushResult.apns_get_timeout,null);
                log.error(e.getMessage(),e);
            }
        } else {
            Throwable e = future.cause();
            onFutureFail(notificationCompositeParam,e);
            if (null != e) {
                log.warn(e.getMessage());
            }
        }
    }

**Comment by qiankunli** [comment]
the log of Http2GoAwayException is

       public void doOperationComplete(Future<PushNotificationResponse<SimpleApnsPushNotification>> future) throws InterruptedException, java.util.concurrent.ExecutionException {
            if (future.isSuccess()) {
                try {
                    PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse =
                            future.get(1, TimeUnit.SECONDS);
                    onFutureSuccess(notificationCompositeParam, pushNotificationResponse);
                }catch (Exception e){
                    notificationCompositeParam.logFail(PushResult.apns_get_timeout,null);
                    log.error(e.getMessage(),e);
                }
            } else {
                Throwable e = future.cause();
                onFutureFail(notificationCompositeParam,e);
                if (null != e) {
                    log.warn(e.getMessage());
                }
            }
        }

**Comment by jchambers** [comment]
I've investigated the issue, and don't think there's anything wrong here. This happens when the server sends a `GOAWAY` frame and pending streams get closed. Regrettably, I think this is just one of those things that can happen under poor network conditions.
