### ISSUE TITLE
ConcurrentModificationException when disconnecting client

### ISSUE THREAD

**Issue by jorcasso** [relayrides/pushy#479]
Just found the following error in our logs

```
java.util.ConcurrentModificationException: null
        at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:734)
        at java.util.IdentityHashMap$ValueIterator.next(IdentityHashMap.java:832)
        at com.turo.pushy.apns.ApnsClientHandler.close(ApnsClientHandler.java:283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465)
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964)
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234)
        at com.turo.pushy.apns.ApnsClient.disconnect(ApnsClient.java:618)
```

Maybe the access to the `responsePromises` map in `ApnsClientHandler` should be synchronized?

**Comment by jchambers** [comment]
Yep. That's definitely a bug. I think this is related to #480; I was under the incorrect impression that channel handlers would run their `close()` method inside of the channel's event loop, which would guarantee serial execution. In reality, it turns out that `close()` (a) can happen on non-event-loop threads and (b) doesn't always happen when the connection shuts down unexpectedly.

Expect a fix here shortly. Thanks for the report, and sorry for the trouble!
