### ISSUE TITLE
An exceptionCaught() event was fired, and it reached at the tail of the pipeline.

### ISSUE THREAD

**Issue by wien-wyc** [relayrides/pushy#491]
Hello, our team are ready to use token-based authentication in sending APNs push notifications. But we got some problems when we use pushy in our test environment. Here are some debug logs:
```
2017-06-30 00:56:25,899 [nioEventLoopGroup-2-2] DEBUG [c.turo.pushy.apns.ApnsClientHandler] -
        Closing channel due to ping timeout.
----
2017-06-30 00:56:25,910 [nioEventLoopGroup-2-2] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Disconnected. Next automatic reconnection attempt in 1 seconds.
----
2017-06-30 00:56:26,912 [nioEventLoopGroup-2-2] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Attempting to reconnect.
----
2017-06-30 00:56:28,364 [nioEventLoopGroup-2-3] INFO  [com.turo.pushy.apns.ApnsClient] -
        Connection to api.development.push.apple.com/17.188.138.73:443 restored.
----
2017-06-30 00:57:47,766 [nioEventLoopGroup-2-1] WARN  [i.n.channel.DefaultChannelPipeline] -
        An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
----
java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
2017-06-30 00:57:47,767 [nioEventLoopGroup-2-1] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Disconnected. Next automatic reconnection attempt in 1 seconds.
2017-06-30 00:57:48,769 [nioEventLoopGroup-2-1] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Attempting to reconnect.
----
2017-06-30 00:57:50,215 [nioEventLoopGroup-2-4] INFO  [com.turo.pushy.apns.ApnsClient] -
        Connection to api.development.push.apple.com/17.188.138.73:443 restored.
----
2017-06-30 00:57:52,376 [nioEventLoopGroup-2-1] DEBUG [c.turo.pushy.apns.ApnsClientHandler] -
        Closing channel due to ping timeout.
----
2017-06-30 01:05:09,569 [nioEventLoopGroup-2-4] WARN  [i.n.channel.DefaultChannelPipeline] -
        An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
----
java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
2017-06-30 01:05:09,571 [nioEventLoopGroup-2-4] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Disconnected. Next automatic reconnection attempt in 1 seconds.
----
2017-06-30 01:05:10,572 [nioEventLoopGroup-2-4] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Attempting to reconnect.
----
2017-06-30 01:05:15,312 [nioEventLoopGroup-2-1] INFO  [com.turo.pushy.apns.ApnsClient] -
        Connection to api.development.push.apple.com/17.188.138.73:443 restored.
----
```
It seems that the reconnection is not stable when ApnsClient touches off the reconnection. The exception always happens after the first reconnection which happens in mid night when no one use the pushy server for some hours. And after first exception happens, the same exception will present occasionally.At the same time, other exception also can be present, like:
```
2017-06-30 03:19:57,036 [nioEventLoopGroup-2-2] DEBUG [c.turo.pushy.apns.ApnsClientHandler] -
        Closing channel due to ping timeout.
----
2017-06-30 03:19:57,039 [nioEventLoopGroup-2-2] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Disconnected. Next automatic reconnection attempt in 1 seconds.
----
2017-06-30 03:19:58,041 [nioEventLoopGroup-2-2] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Attempting to reconnect.
----
2017-06-30 03:20:09,304 [nioEventLoopGroup-2-3] WARN  [i.n.h.s.ApplicationProtocolNegotiationHandler] -
        [id: 0x07034b62, L:/121.43.60.132:13110 - R:api.development.push.apple.com/17.188.138.73:443] TLS handshake failed:
----
javax.net.ssl.SSLException: handshake timed out
        at io.netty.handler.ssl.SslHandler.handshake(...)(Unknown Source)
2017-06-30 03:20:09,307 [nioEventLoopGroup-2-3] INFO  [com.turo.pushy.apns.ApnsClient] -
        Failed to connect.
----
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
        at com.turo.pushy.apns.ApnsClient$3.operationComplete(ApnsClient.java:395)
        at com.turo.pushy.apns.ApnsClient$3.operationComplete(ApnsClient.java:387)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1058)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:686)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:664)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
        at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1657)
        at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1646)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
        at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:1646)
        at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1457)
        at io.netty.handler.ssl.SslHandler.close(SslHandler.java:613)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465)
        at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.handshakeFailure(ApplicationProtocolNegotiationHandler.java:116)
        at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.userEventTriggered(ApplicationProtocolNegotiationHandler.java:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
        at io.netty.handler.ssl.SslUtils.notifyHandshakeFailure(SslUtils.java:246)
        at io.netty.handler.ssl.SslHandler.notifyHandshakeFailure(SslHandler.java:1415)
        at io.netty.handler.ssl.SslHandler.access$1200(SslHandler.java:160)
        at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:1584)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
2017-06-30 03:20:09,307 [nioEventLoopGroup-2-3] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Disconnected. Next automatic reconnection attempt in 1 seconds.
----
```
and
```
2017-06-30 03:32:06,705 [nioEventLoopGroup-2-3] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Attempting to reconnect.
----
2017-06-30 03:32:13,709 [nioEventLoopGroup-2-4] INFO  [com.turo.pushy.apns.ApnsClient] -
        Failed to connect.
----
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: api.development.push.apple.com/17.188.138.73:443
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out
        ... 11 common frames omitted
2017-06-30 03:32:13,710 [nioEventLoopGroup-2-4] DEBUG [com.turo.pushy.apns.ApnsClient] -
        Disconnected. Next automatic reconnection attempt in 1 seconds.
----
```
Our pushy server create two ApnsClient which are used to push notification in turn. I count the exception more than 10 times last night. Another interesting thing is all kinds of exceptions mostly happen in 0-8 o'clock(GMT+8) for a few days. Finally, we are in China. Wish to your reply.

**Comment by jchambers** [comment]
Sounds like this is just an artifact of poor network conditions (regrettably, we see this a lot from China—it appears that there are no APNs servers there). The uncaught exception, while annoying, doesn't appear to be anything to worry about.

To be clear, is you concern just about the uncaught exception, or are you having trouble restoring the connection in general?

**Comment by wien-wyc** [comment]
@jchambers Our concern is just about the uncaught exception, for these exceptions can be confused with other truly exceptions in the same project. Can you provide some suggestions to ignore these exceptions, or will you decide to deal with these uncaught exceptions in next versions?

**Comment by jchambers** [comment]
Thanks for clarifying. I'll see if we can find a graceful way to identify and handle those exceptions within Pushy itself.

**Comment by jchambers** [comment]
I've opened #602, which I believe should resolve the vast majority of the cases of uncaught exceptions reaching the end of the pipeline. We intend to put out a release shortly; please let us know if this problem persists after v0.13.0 and we'll reopen this ticket.
