### ISSUE TITLE
ClientNotConnectedException When Creating ApnsClients

### ISSUE THREAD

**Issue by fredalxin** [relayrides/pushy#503]
when I use pushy 10.1 in particular environment,I found the ClientNotConnectedException when creating some ApnsClients,while the othes is correct.Exception caused at
`    private static final ClientNotConnectedException NOT_CONNECTED_EXCEPTION = new ClientNotConnectedException();
`.
The detail shows here:
```
Caused by: com.turo.pushy.apns.ClientNotConnectedException: null
        at com.turo.pushy.apns.ApnsClient.<clinit>(ApnsClient.java:152) ~[pushy-0.10.1.jar:na]
        at com.turo.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:420) ~[pushy-0.10.1.jar:na]
        at com.arcsoft.upns.consumer.pushy.ApnsClientPool.create(ApnsClientPool.java:60) ~[upns-consumer-3.0.1.jar:na]
        at com.arcsoft.upns.consumer.pushy.ApnsClientPool.create(ApnsClientPool.java:26) ~[upns-consumer-3.0.1.jar:na]
        at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363) ~[commons-pool2-2.4.2.jar:2.4.2]
        at com.arcsoft.upns.consumer.pushy.PushySenderServiceImpl.pushSingleNotification(PushySenderServiceImpl.java:102) [upns-consumer-3.0.1.jar:na]
        at com.arcsoft.upns.consumer.pushy.PushyPushNotificationTask.doRealPush(PushyPushNotificationTask.java:32) [upns-consumer-3.0.1.jar:na]
        at com.arcsoft.upns.consumer.AbstractConsumerTask.doPush(AbstractConsumerTask.java:167) [upns-consumer-3.0.1.jar:na]
        at com.arcsoft.upns.consumer.AbstractConsumerTask$NotiRabbitHandler.handleMsg(AbstractConsumerTask.java:128) [upns-consumer-3.0.1.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
        ... 20 common frames omitted
```
The strange thing is ,in other environment,everything goes well.

**Comment by jchambers** [comment]
This sounds like you just have a poor network connection. We've observed this happening to a lot of users in Beijing in particular. I don't think there's anything we can do about this in Pushy itself, but the situation should become less problematic after #492.

For now, I'm going to close this issue because I don't think there's anything wrong per se. Please leave a comment here if you feel differently and we'll happily reassess the situation!
