### ISSUE TITLE
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.

### ISSUE THREAD

**Issue by sapatel10080** [relayrides/pushy#523]
I get below error after upgrading pushy from 0.9 to 0.11.

java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.

**Comment by jchambers** [comment]
I'm sorry, but that's simply not enough information for us to be able to help. How often does this happen? Is there anything else in the logs to go by?

**Comment by jchambers** [comment]
Closing due to lack of information. @sapatel10080 if you get a chance to provide more information, please leave a comment here and we'll happily revisit the issue.

**Comment by TimYi** [comment]
I update pushy from 0.9 to 0.11(0.9 version has memory leak issue), and get the same error. Pushy runs under tomcat environment. I'll check this problem tommrrow.

**Comment by TimYi** [comment]
@jchambers I add only pushy11.3 in my pom dependency. My unit test send message successfuly.
But under tomcat environment, I got this warn:
```
[WARN ] 2017-10-14 10:38:02.251 [nioEventLoopGroup-3-1] ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x26bd62b8]
java.lang.RuntimeException: ALPN unsupported. Is your classpath configured correctly? For Conscrypt, add the appropriate Conscrypt JAR to classpath and set the security provider. For Jetty-ALPN, see http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$FailureWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:122) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:245) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:215) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:913) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:905) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at com.turo.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:98) ~[pushy-0.11.3.jar:?]
	at com.turo.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:88) ~[pushy-0.11.3.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:476) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:332) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at com.turo.pushy.apns.ApnsChannelFactory$3.run(ApnsChannelFactory.java:176) [pushy-0.11.3.jar:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by TimYi** [comment]
I solved my problem, see
[](https://github.com/relayrides/pushy/issues/542)

**Comment by sapatel10080** [comment]
Sorry for late response. I resolved my issue. We had a conflicting tcnative library in our tomcat which was needed in previous version of Pushy. After removing that conflicting tcnative library, it resolved the issue.
