### ISSUE TITLE
Running inside Spring Boot (java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider)

### ISSUE THREAD

**Issue by ryan2x** [relayrides/pushy#541]
When I ran Pushy inside Spring Boot (1.5.7), ApnsClient could not be initialized. I am using version pushy 0.11.0

I read the wiki on running Pushy inside container, and that does not help.

Here is the exception stack:

```
2017-10-13 21:33:33.314  INFO 11 --- [nio-9096-exec-1] com.turo.pushy.apns.SslUtil              : Native SSL provider not available; will use JDK SSL provider.
2017-10-13 21:33:34.004 ERROR 11 --- [nio-9096-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider] with root cause

java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111-internal]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111-internal]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[notification-services-1.0-SNAPSHOT.jar:na]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111-internal]
        at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:26) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:283) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:261) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:283) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:261) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:751) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:406) ~[netty-all-4.1.8.Final.jar!/:4.1.8.Final]
        at com.turo.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:513) ~[pushy-0.11.3.jar!/:na]
		......
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.20.jar!/:8.5.20]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.20.jar!/:8.5.20]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, it sounds like you need to add [`alpn-api`](http://search.maven.org/#artifactdetails%7Corg.eclipse.jetty.alpn%7Calpn-api%7C1.1.3.v20160715%7Cjar) to your classpath, but I'm not sure why that isn't happening by default.
