### ISSUE TITLE
Unable to load the library 'netty_tcnative_linux_x86_64'

### ISSUE THREAD

**Issue by Fomikadze** [relayrides/pushy#578]
Hi!
I get this exception while trying to run application, whit pushy client. 

- My current pushy version 0.12.0.
- My java version is:
    java version "1.8.0_65"
    Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
- Application is runnig Red Hat Enterprise Linux Server release 7.1 (Maipo).

I initiate ApnsClient like this, with SocksProxy:

```java
apnsClient = new ApnsClientBuilder()
        .setSigningKey(ApnsSigningKey.loadFromPkcs8File(new File(APNS_CERTIFICATE_PATH),
                TEAM_ID, KEY_ID))
        .setProxyHandlerFactory(new Socks5ProxyHandlerFactory(
                new InetSocketAddress(PROXY_HOST, PROXY_PORT)))
        .setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST)
        .build();
```

**How can I fix problem with netty_tcnative_linux_x86_64 library?**

```
2018-02-05 17:58:07,531 [kaspi.red.units.EDT-km-core-2] D     i.n.u.i.NativeLibraryLoader - Unable to load the library 'netty_tcnative_linux_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864) ~[?:1.8.0_65]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_65]
        at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_65]
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[message-core.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:263) ~[message-core.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:255) ~[message-core.jar:?]
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:233) ~[message-core.jar:?]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124) ~[message-core.jar:?]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:85) ~[message-core.jar:?]
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:421) ~[message-core.jar:?]
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:89) ~[message-core.jar:?]
        at com.turo.pushy.apns.SslUtil.getSslProvider(SslUtil.java:49) ~[message-core.jar:?]
        at com.turo.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:517) ~[message-core.jar:?]
        at kz.kaspi.message.channels.model.push.apns.ApnsService.buildClient(ApnsService.java:77) ~[message-core.jar:?]
        at kz.kaspi.message.channels.model.push.apns.ApnsService.init(ApnsService.java:88) ~[message-core.jar:?]
        at kz.kaspi.message.channels.providers.PushNotificationUnit.<init>(PushNotificationUnit.java:56) ~[message-core.jar:?]
        at kz.kaspi.message.channels.providers.PushNotificationUnit.init(PushNotificationUnit.java:72) ~[message-core.jar:?]
        at kz.kaspi.message.channels.ChannelUnit.<init>(ChannelUnit.java:117) ~[message-core.jar:?]
        at kz.kaspi.message.channels.ChannelUnit$ChannelUnitProvider.createUnit(ChannelUnit.java:837) ~[message-core.jar:?]
        at kz.kaspi.red.processing.units.SystemInfo.lambda$submitCommands$34(SystemInfo.java:320) ~[message-core.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_65]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_65]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_65]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_65]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_65]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_65]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_65]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_65]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_65]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_65]
        at kz.kaspi.red.processing.units.SystemInfo.submitCommands(SystemInfo.java:313) [message-core.jar:?]
        at kz.kaspi.red.processing.units.EventDispatchThread$ExecutorBehaviour.proceed(EventDispatchThread.java:157) [message-core.jar:?]
        at kz.kaspi.red.processing.units.EventDispatchThread.run(EventDispatchThread.java:39) [message-core.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
2018-02-05 17:58:07,545 [kaspi.red.units.EDT-km-core-2] D     i.n.u.i.NativeLibraryLoader - netty_tcnative_linux_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864) ~[?:1.8.0_65]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_65]
        at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_65]
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[message-core.jar:?]
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243) ~[message-core.jar:?]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124) ~[message-core.jar:?]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:85) ~[message-core.jar:?]
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:421) ~[message-core.jar:?]
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:89) ~[message-core.jar:?]
        at com.turo.pushy.apns.SslUtil.getSslProvider(SslUtil.java:49) ~[message-core.jar:?]
        at com.turo.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:517) ~[message-core.jar:?]
        at kz.kaspi.message.channels.model.push.apns.ApnsService.buildClient(ApnsService.java:77) ~[message-core.jar:?]
        at kz.kaspi.message.channels.model.push.apns.ApnsService.init(ApnsService.java:88) ~[message-core.jar:?]
        at kz.kaspi.message.channels.providers.PushNotificationUnit.<init>(PushNotificationUnit.java:56) ~[message-core.jar:?]
        at kz.kaspi.message.channels.providers.PushNotificationUnit.init(PushNotificationUnit.java:72) ~[message-core.jar:?]
        at kz.kaspi.message.channels.ChannelUnit.<init>(ChannelUnit.java:117) ~[message-core.jar:?]
        at kz.kaspi.message.channels.ChannelUnit$ChannelUnitProvider.createUnit(ChannelUnit.java:837) ~[message-core.jar:?]
        at kz.kaspi.red.processing.units.SystemInfo.lambda$submitCommands$34(SystemInfo.java:320) ~[message-core.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_65]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_65]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_65]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_65]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_65]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_65]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_65]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_65]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_65]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_65]
        at kz.kaspi.red.processing.units.SystemInfo.submitCommands(SystemInfo.java:313) [message-core.jar:?]
        at kz.kaspi.red.processing.units.EventDispatchThread$ExecutorBehaviour.proceed(EventDispatchThread.java:157) [message-core.jar:?]
        at kz.kaspi.red.processing.units.EventDispatchThread.run(EventDispatchThread.java:39) [message-core.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
        Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864) ~[?:1.8.0_65]
                at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_65]
                at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_65]
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[message-core.jar:?]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:263) ~[message-core.jar:?]
                at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:255) ~[message-core.jar:?]
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:233) ~[message-core.jar:?]
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124) ~[message-core.jar:?]
                at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:85) ~[message-core.jar:?]
                at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:421) ~[message-core.jar:?]
                at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:89) ~[message-core.jar:?]
                at com.turo.pushy.apns.SslUtil.getSslProvider(SslUtil.java:49) ~[message-core.jar:?]
                at com.turo.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:517) ~[message-core.jar:?]
                at kz.kaspi.message.channels.model.push.apns.ApnsService.buildClient(ApnsService.java:77) ~[message-core.jar:?]
                at kz.kaspi.message.channels.model.push.apns.ApnsService.init(ApnsService.java:88) ~[message-core.jar:?]
                at kz.kaspi.message.channels.providers.PushNotificationUnit.<init>(PushNotificationUnit.java:56) ~[message-core.jar:?]
                at kz.kaspi.message.channels.providers.PushNotificationUnit.init(PushNotificationUnit.java:72) ~[message-core.jar:?]
                at kz.kaspi.message.channels.ChannelUnit.<init>(ChannelUnit.java:117) ~[message-core.jar:?]
                at kz.kaspi.message.channels.ChannelUnit$ChannelUnitProvider.createUnit(ChannelUnit.java:837) ~[message-core.jar:?]
                at kz.kaspi.red.processing.units.SystemInfo.lambda$submitCommands$34(SystemInfo.java:320) ~[message-core.jar:?]
                at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_65]
                at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_65]
                at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_65]
                at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_65]
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_65]
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_65]
                at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_65]
                at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_65]
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_65]
                at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_65]
                at kz.kaspi.red.processing.units.SystemInfo.submitCommands(SystemInfo.java:313) [message-core.jar:?]
                at kz.kaspi.red.processing.units.EventDispatchThread$ExecutorBehaviour.proceed(EventDispatchThread.java:157) [message-core.jar:?]
                at kz.kaspi.red.processing.units.EventDispatchThread.run(EventDispatchThread.java:39) [message-core.jar:?]
                at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by jchambers** [comment]
Sorry; I don't know, and I think this is actually a better question for the Netty folks. I think their preferred Q&A channel is https://stackoverflow.com/questions/tagged/netty.
