### ISSUE TITLE
Notification write failed, but no response promise found.

### ISSUE THREAD

**Issue by deepsky777** [relayrides/pushy#579]
version 0.10

Recently, I've got following errors on production. I don't know how to fix it. Can you figure out what the problem is?
ref. these errors occur many time at once.

```
2018/02/12 09:16:18.341 ERROR (ApnsClientHandler.java:198) - Notification write failed, but no response promise found.
2018/02/12 09:16:18.341 ERROR (ApnsClientHandler.java:198) - Notification write failed, but no response promise found.
2018/02/12 09:16:18.342 ERROR (ApnsClientHandler.java:198) - Notification write failed, but no response promise found.
2018/02/12 09:16:18.342 ERROR (ApnsClientHandler.java:198) - Notification write failed, but no response promise found.
2018/02/12 09:16:18.342 ERROR (ApnsClientHandler.java:198) - Notification write failed, but no response promise found.
2018/02/12 09:16:18.342 ERROR (ApnsClientHandler.java:198) - Notification write failed, but no response promise found.
2018/02/12 09:16:18.342 ERROR (ApnsClientHandler.java:198) - Notification write failed, but no response promise found.
2018/02/12 09:16:18.350  WARN (Slf4JLogger.java:146) - Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@52433c20(success)
java.util.ConcurrentModificationException
	at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:734)
	at java.util.IdentityHashMap$ValueIterator.next(IdentityHashMap.java:832)
	at com.turo.pushy.apns.ApnsClientHandler.close(ApnsClientHandler.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234)
	at com.turo.pushy.apns.ApnsClientHandler$3.operationComplete(ApnsClientHandler.java:256)
	at com.turo.pushy.apns.ApnsClientHandler$3.operationComplete(ApnsClientHandler.java:250)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:387)
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryFailure(Http2CodecUtil.java:307)
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
	at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:675)
	at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:293)
	at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:616)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:667)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:867)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:638)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jchambers** [comment]
Looks straightforward. Thanks for the report, and sorry for the trouble.

**Comment by jchambers** [comment]
I take it back; I just noticed that you're using an older version of Pushy. I think this has long since been fixed. Updating to the latest version should solve the problem.
