### ISSUE TITLE
pushy 0.12.0 throw NoSuchMethod Exception

### ISSUE THREAD

**Issue by devhak2** [relayrides/pushy#582]
I'm using Gradle for managing dependencies.
When i use pushy to send token based message, it throws the following exception periodically.

java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2ConnectionEncoder.writePing(Lio/netty/channel/ChannelHandlerContext;ZLio/netty/buffer/ByteBuf;Lio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture;
	at com.turo.pushy.apns.ApnsClientHandler.userEventTriggered(ApnsClientHandler.java:269) ~[pushy-0.12.0.jar!/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [netty-transport-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [netty-transport-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [netty-transport-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371) [netty-handler-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:494) [netty-handler-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466) [netty-handler-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

Could you have the solution?

To more specific, i added my dependencies.

compile('org.springframework.boot:spring-boot-starter-cache')
compile('org.springframework.boot:spring-boot-starter-data-jpa')
compile('org.springframework.boot:spring-boot-starter-data-redis')
compile('org.springframework.boot:spring-boot-starter-logging')
compile group: 'org.mariadb.jdbc', name: 'mariadb-java-client', version: '2.2.0'
compile('com.zaxxer:HikariCP')
compileOnly('org.projectlombok:lombok')
compile group: 'com.turo', name: 'pushy', version: '0.12.0'
compile group: 'com.turo', name: 'pushy-dropwizard-metrics-listener', version: '0.12.0'
compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.4'
compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.4'
compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.9.4'
compile('com.github.ben-manes.caffeine:caffeine')

**Comment by devhak2** [comment]
I found out.
DefaultHttp2ConnectionEncoder in io.netty.handler.codec.http2:4.1.22 does not have the writePing method.
DefaultHttp2ConnectionEncoder in io.netty.handler.codec.http2:4.1.19 has the writePing method.
Your pom.xml doesn't specify version of io.netty.handler.codec.http2. So, Gradle(or Maven) downloads the latest version.

**Comment by jchambers** [comment]
Well, two things here:

1. Pushy's POM most definitely does call out an explicit version for Netty: https://github.com/relayrides/pushy/blob/master/pom.xml#L109. I respect that you ran into some trouble, but I don't think a missing version was the cause; we should definitely keep an eye out in case this happens to other folks.
2. @bugix has kindly opened a pull request (#581) to update to Netty 4.1.22, which uses the latest `ping`-related methods.

**Comment by bugix** [comment]
In my case the Netty 4.1.22 dependency got pulled in by spring-boot 2.0.0. If time permits, please consider a release containing this dependency bump.
