### ISSUE TITLE
Exception sending push notification

### ISSUE THREAD

**Issue by srinisubramanian** [relayrides/pushy#630]
Environment: Wildfly 10/JDK 1.8
Server: Windows Server 2008 R2
Jars: Pushy 0.11.3, Netty 4.1.16 netty-tcnative-boringssl-static-2.0.6.Final

Notes:
1. Push certificate etc are all verified and working
2. Identical setup (copy of jars/ear file and same JDK) works on Linux (Centos/Ubuntu) servers and on Windows Server 2012 also
3. Connectivity to APNS servers were tested using the Apple docs and everything seems to be fine

Issue: Whenever a push notification is attempted to be sent, it fails with a Java exception.  The issue occurs on a Windows Server 2008 R2 server.  We set netty and pushy log  levels to FINE and below the extract.

```
14:03:28,965 WARNING {10.81.3.207} {} {CHYME} {SYC1400628929138567516201862414} [io.netty.handler.ssl.ApplicationProtocolNegotiationHandler] (nioEventLoopGroup-5-1) [id: 0x972d66e0, L:0.0.0.0/0.0.0.0:64824 ! R:api.push.apple.com/17.188.147.162:443] TLS handshake failed:: java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source) [netty-all-4.1.16.Final.jar:4.1.16.Final]

14:03:28,966 ERROR  [stderr] (pool-6-thread-2) java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.

14:03:28,966 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)

14:03:28,966 ERROR  [stderr] (pool-6-thread-2) 	at com.unvired.ump.fa.APNSFrontendAdapter.notification(APNSFrontendAdapter.java:275)

14:03:28,967 ERROR  [stderr] (pool-6-thread-2) 	at com.unvired.ump.fa.APNSFrontendAdapter.pushMessage(APNSFrontendAdapter.java:212)

14:03:28,967 ERROR  [stderr] (pool-6-thread-2) 	at com.unvired.ump.core.mdb.IubNotificationBean.processMessage(IubNotificationBean.java:51)

14:03:28,967 ERROR  [stderr] (pool-6-thread-2) 	at com.unvired.ump.core.mdb.IubNotificationBean.access$000(IubNotificationBean.java:16)

14:03:28,967 ERROR  [stderr] (pool-6-thread-2) 	at com.unvired.ump.core.mdb.IubNotificationBean$1.run(IubNotificationBean.java:28)

14:03:28,967 ERROR  [stderr] (pool-6-thread-2) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

14:03:28,967 ERROR  [stderr] (pool-6-thread-2) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

14:03:28,967 ERROR  [stderr] (pool-6-thread-2) 	at java.lang.Thread.run(Thread.java:745)

14:03:28,968 ERROR  [stderr] (pool-6-thread-2) Caused by: java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.

14:03:28,968 ERROR  [stderr] (pool-6-thread-2) 	at com.turo.pushy.apns.ApnsChannelFactory$3$2.operationComplete(ApnsChannelFactory.java:198)

14:03:28,968 ERROR  [stderr] (pool-6-thread-2) 	at com.turo.pushy.apns.ApnsChannelFactory$3$2.operationComplete(ApnsChannelFactory.java:192)

14:03:28,969 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)

14:03:28,969 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:764)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:740)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:611)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:85)

14:03:28,970 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:142)

14:03:28,971 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)

14:03:28,971 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)

14:03:28,971 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)

14:03:28,971 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)

14:03:28,971 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)

14:03:28,971 ERROR  [stderr] (pool-6-thread-2) 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)

14:03:28,971 ERROR  [stderr] (pool-6-thread-2) 	... 1 more
```

Any idea what the issue might be and what we should be checking for?

**Comment by srinisubramanian** [comment]
Thanks for the note Jon.  I posted to the mailing list now.  Also noticed that a few others have recently reported similar issues but no answers yet.
