### ISSUE TITLE
IOException when setting client credentials

### ISSUE THREAD

**Issue by carial-2002** [relayrides/pushy#642]
I am using Pushy 0.13.4. I had the following exception when calling .setClientCredentials:

Security providers:
	- SUN
	- SunRsaSign
	- SunEC
	- SunJSSE
	- SunJCE
	- SunJGSS
	- SunSASL
	- XMLDSig
	- SunPCSC

Key store contents (1 entries):
	-veeu ios: java.security.KeyStore$PrivateKeyEntry
2018-09-18 16:01:21,446 ERROR com.cootek.gct.backend.pushsender.kafka.KafkaDispatcher:100 - error when creating apns client
java.io.IOException: Short read of DER length
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:582)
	at sun.security.util.DerValue.init(DerValue.java:391)
	at sun.security.util.DerValue.<init>(DerValue.java:332)
	at sun.security.util.DerValue.<init>(DerValue.java:345)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1938)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.turo.pushy.apns.P12Util.getFirstPrivateKeyEntryFromP12InputStream(P12Util.java:62)
	at com.turo.pushy.apns.ApnsClientBuilder.setClientCredentials(ApnsClientBuilder.java:221)

I followed the steps in https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_certificate-based_connection_to_apns to generate .p12 certificate file. Could you take a look to see what's wrong?

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

**Comment by WonderLand33** [comment]
Same to me .
