### ISSUE TITLE
Exception cause while sending notification payload to apns gateway {} java.lang.IllegalStateException: Channel pool has closed and no more channels may be acquired.

### ISSUE THREAD

**Issue by rohitsahay2000** [relayrides/pushy#645]
Hi,
We are getting the below errors while sending notifications
`Exception cause while sending notification payload to apns gateway {}
java.lang.IllegalStateException: Channel pool has closed and no more channels may be acquired.
	at com.turo.pushy.apns.ApnsChannelPool.<clinit>(ApnsChannelPool.java:68) ~[pushy-0.13.3.jar:?]
	at com.turo.pushy.apns.ApnsClient.<init>(ApnsClient.java:171) ~[pushy-0.13.3.jar:?]
	at com.turo.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:546) ~[pushy-0.13.3.jar:?]
	at com.fiberlink.push.notification.service.impl.PushNotificationServiceIOS.getAPNSClient(PushNotificationServiceIOS.java:493) ~[push-notification-service-10.70-SNAPSHOT.jar:10.70-SNAPSHOT]
	at com.fiberlink.push.notification.service.impl.PushNotificationServiceIOS.sendPushyNotification(PushNotificationServiceIOS.java:149) ~[push-notification-service-10.70-SNAPSHOT.jar:10.70-SNAPSHOT]
	at com.fiberlink.push.notification.service.impl.PushNotificationServiceIOS.sendNotification(PushNotificationServiceIOS.java:79) ~[push-notification-service-10.70-SNAPSHOT.jar:10.70-SNAPSHOT]
	at com.fiberlink.push.notification.service.impl.PushNotificationServiceIOS.sendNotification(PushNotificationServiceIOS.java:408) ~[push-notification-service-10.70-SNAPSHOT.jar:10.70-SNAPSHOT]
	at com.fiberlink.notification.ios.service.impl.NotificationUtilService.performBatchedNotifications(NotificationUtilService.java:217) ~[mdm-notification.jar:10.70-SNAPSHOT]
	at com.fiberlink.notification.ios.service.impl.Notific`

The number of these errors are around 150 out of 50k ~60k notifications we send via pushy everyday. How to resolve it?

**Comment by jchambers** [comment]
That [exception](https://github.com/relayrides/pushy/blob/3384c4a6d2c6002280398ef2ff5eb0c9258a1f13/pushy/src/main/java/com/turo/pushy/apns/ApnsChannelPool.java#L68-L69) is only thrown if the channel pool tries to open a channel after the pool has already been shut down. It sounds like you're trying to send notifications after calling `ApnsClient#close()` or, more likely, that you're calling `ApnsClient#close()` before all outstanding notifications have been resolved.

Do you have something in place that makes sure that all of the `Futures` returned by the `sendNotification` method have finished by the time you call `ApnsClient#close()`?

**Comment by rohitsahay2000** [comment]
Hi,
Thanks for you reply. Would like to give more details of what we are doing:
1. Our production code sends notifications to around 10 million devices
across 10k customers everyday. We are using notnoop library there to send
notifications which is on apns v1.
2. We are migrating to apns v2, and thus started using pushy. Currently the
code is in our qa and staging environment where we are doing load testing
before it goes live in production.

3. The code is like this:
We have a class named as PushNotificationConnection which contains
ApnsClient . This connection object is one per organization/customer.

*public* *class* PushNotificationConnection *implements* Serializable {



        ------------------------------------


*private* ApnsClient apnsClient;

        *private* Long organizaationId;

        ------------------------------------

        ------------------------------------
}

We don't create PushNotificationConnection objects every time we send
notifications. Instead it goes to cache. Once this object is evicted from
cache, the apns client is closed during garbage collection of this object.
Code snippet:

@Override

*protected* *void* finalize() *throws* Throwable {

*if*(*null*!=apnsClient) {

*logger*.debug("APNS Pushy Connection is getting closed by GC for Org Id:
{}" , orgId);

apnsClient.close();

apnsClient = *null*;

}

*super*.finalize();
}

As per whatever you have said, it might happen that the notifications are
still in queue which pushy maintains, and the apns client gets closed
because the object has been evicted from cache and gets eligible for GC.

We tried using this which is mentioned in pushy'd documentation:

final Future<Void> closeFuture = apnsClient.close();
closeFuture.await();


But since this is a blocking call, this makes the processing extremely slow.

Please let us know what we can do here seeing the scale of the
notifications we send.

Thanks,
Rohit

**Comment by rohitsahay2000** [comment]
Hi,
Thanks for you reply. Would like to give more details of what we are doing:
1. Our production code sends notifications to around 10 million devices across 10k customers everyday. We are using notnoop library there to send notifications which is on apns v1.
2. We are migrating to apns v2, and thus started using pushy. Currently the code is in our qa and staging environment where we are doing load testing before it goes live in production.

3. The code is like this:
We have a class named as PushNotificationConnection which contains ApnsClient . This connection object is one per organization/customer.

`public class PushNotificationConnection implements Serializable {

        

        ------------------------------------



	private ApnsClient apnsClient;

        private Long organizaationId;

        ------------------------------------

        ------------------------------------

}`

We don't create PushNotificationConnection objects every time we send notifications. Instead it goes to cache. Once this object is evicted from cache, the apns client is closed during garbage collection of this object. Code snippet:

`@Override

	protected void finalize() throws Throwable {

		if(null!=apnsClient) {

			logger.debug("APNS Pushy Connection is getting closed by GC for Org Id: {}" , orgId);

			apnsClient.close();

			apnsClient = null;		

		}

		super.finalize();

}`

As per whatever you have said, it might happen that the notifications are still in queue which pushy maintains, and the apns client gets closed because the object has been evicted from cache and gets eligible for GC.

We tried using this which is mentioned in pushy'd documentation:
final Future<Void> closeFuture = apnsClient.close();
closeFuture.await();

But since this is a blocking call, this makes the processing extremely slow.

Please let us know what we can do here seeing the scale of the notifications we send.

Thanks,
Rohit

**Comment by jchambers** [comment]
For posterity, I've answered these questions [on the mailing list](https://groups.google.com/d/msg/pushy-apns/aR6F2Qq75v4/Jx9ManCiAwAJ).
