### ISSUE TITLE
java.lang.AbstractMethodError at io.netty.internal.tcnative.SSL.readFromSSL

### ISSUE THREAD

**Issue by tylzvs007** [relayrides/pushy#687]
And error occured when i updated pushy to the latest version:
java.lang.AbstractMethodError
	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[netty-tcnative-boringssl-static-2.0.20.Final-linux-x86_64.jar:2.0.20.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:486) ~[netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1025) ~[netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1132) ~[netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1175) ~[netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216) ~[netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1189) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1223) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]

pom:
        <dependency>
        	<groupId>io.netty</groupId>
        	<artifactId>netty-all</artifactId>
        	<version>4.1.23.Final</version>
        </dependency>
        <dependency>
    		<groupId>io.netty</groupId>
    		<artifactId>netty-tcnative-boringssl-static</artifactId>
    		<version>2.0.20.Final</version>
    		
                <classifier>linux-x86_64</classifier>
	</dependency>

java version "1.7.0_76"
Could you  please help me with this issue?

**Comment by tylzvs007** [comment]
it seemed that i have made a mistake. i  upgraded netty version to  4.1.32.Final and solved this problem. if  u upgrade  the version of tcnative, netty verison must be also upgraded to the  specified 
version. It's a exciting thing to find that the lastest verion of  tcnative have  resolved the os  adaptation problem so we will not  need to use the 'classifier' lable to specify  os, just like this: 
<classifier>linux-x86_64</classifier>

**Comment by iamchairs** [comment]
I haven't had the same luck. I am using java 11 with netty 4.1.32.Final and tcnative 2.0.20.Final and getting the same error you're showing.

**Comment by iamchairs** [comment]
I need tcnative enabled for another application but i'd be fine turning it off for pushy if that's possible.
