### ISSUE TITLE
Netty unable to resolve DNS for api.push.apple.com

### ISSUE THREAD

**Issue by anuraggupta** [relayrides/pushy#711]
Running locally on my macbook pro I'm getting dns look up issue. 
But nslookup gives proper results

```
$ nslookup api.push.apple.com
Server:		10.40.4.247
Address:	10.40.4.247#53

Non-authoritative answer:
api.push.apple.com	canonical name = api.push-apple.com.akadns.net.
Name:	api.push-apple.com.akadns.net
Address: 17.188.145.163
Name:	api.push-apple.com.akadns.net
Address: 17.188.153.32
Name:	api.push-apple.com.akadns.net
Address: 17.188.152.30
Name:	api.push-apple.com.akadns.net
Address: 17.188.148.35
Name:	api.push-apple.com.akadns.net
Address: 17.188.149.27
Name:	api.push-apple.com.akadns.net
Address: 17.188.158.32
Name:	api.push-apple.com.akadns.net
Address: 17.188.157.157
Name:	api.push-apple.com.akadns.net
Address: 17.188.150.28

```
```
{"app_module":"NotificationWorker","environment":"local","level":"DEBUG","timestamp":"2019-08-08T00:25:23,973","thread_name":"ioEventLoopGroup-2-1","logger_name":"y.resolver.dns.DnsQueryContext","message":"[id: 0x953c6a9a] WRITE: UDP, [9063: /2001:4860:4860:0:0:0:0:8888:53], DefaultDnsQuestion(api.push.apple.com. IN A)"}
{"app_module":"NotificationWorker","environment":"local","level":"DEBUG","timestamp":"2019-08-08T00:25:23,974","thread_name":"ioEventLoopGroup-2-1","logger_name":"y.resolver.dns.DnsQueryContext","message":"[id: 0x953c6a9a] WRITE: UDP, [21393: /2001:4860:4860:0:0:0:0:8888:53], DefaultDnsQuestion(api.push.apple.com. IN AAAA)"}
{"app_module":"NotificationWorker","environment":"local","level":"DEBUG","timestamp":"2019-08-08T00:25:23,975","thread_name":"ioEventLoopGroup-2-1","logger_name":"y.resolver.dns.DnsQueryContext","message":"[id: 0x953c6a9a] WRITE: UDP, [48743: /2001:4860:4860:0:0:0:0:8844:53], DefaultDnsQuestion(api.push.apple.com. IN A)"}
{"app_module":"NotificationWorker","environment":"local","level":"DEBUG","timestamp":"2019-08-08T00:25:23,975","thread_name":"ioEventLoopGroup-2-1","logger_name":"y.resolver.dns.DnsQueryContext","message":"[id: 0x953c6a9a] WRITE: UDP, [27138: /2001:4860:4860:0:0:0:0:8844:53], DefaultDnsQuestion(api.push.apple.com. IN AAAA)"}
{"app_module":"NotificationWorker","environment":"local","level":"ERROR","timestamp":"2019-08-08T00:25:23,977","x-request-id":"19d00d3c-e032-4107-8f72-d3a366dcc9b5","thread_name":" spring-scheduler-16","logger_name":"mmon.push.client.ANSAPNSClient","message":"Error while sending notification for appId [anuragup-fcm] notificationId [48cef1b3-f307-4938-999a-d6ae7a697357] deviceId [43fc2bb1-e944-4bd0-a033-6d497d67d756]"}
java.util.concurrent.ExecutionException: java.net.UnknownHostException: failed to resolve 'api.push.apple.com' after 4 queries 
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	============REMOVED SOME TRACE==========================
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.UnknownHostException: failed to resolve 'api.push.apple.com' after 4 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:228) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsQueryContext.onQueryWriteCompletion(DnsQueryContext.java:162) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsQueryContext.access$200(DnsQueryContext.java:42) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:154) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:151) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:721) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:306) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:286) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:159) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:928) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:356) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1370) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:978) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:241) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1137) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:299) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:205) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1038) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1016) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:967) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:935) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:71) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:56) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.RoundRobinInetAddressResolver.doResolve(RoundRobinInetAddressResolver.java:57) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:204) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:166) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:120) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at com.turo.pushy.apns.ApnsChannelFactory$3.run(ApnsChannelFactory.java:209) ~[pushy-0.13.9.jar:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	... 1 more
Caused by: io.netty.resolver.dns.DnsNameResolverException: [/2001:4860:4860:0:0:0:0:8844:53] failed to send a query via UDP (no stack trace available)
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:584) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:546) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:529) ~[?:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:292) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:928) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:356) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1370) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:978) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:241) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1137) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:299) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:205) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1038) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1016) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:967) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:935) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:71) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:56) ~[netty-resolver-dns-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.RoundRobinInetAddressResolver.doResolve(RoundRobinInetAddressResolver.java:57) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108) ~[netty-resolver-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:204) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:166) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:120) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at com.turo.pushy.apns.ApnsChannelFactory$3.run(ApnsChannelFactory.java:209) ~[pushy-0.13.9.jar:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
	... 1 more

```

**Comment by anuraggupta** [comment]
An update 
I downgraded netty to previous version i.e 4.1.32.Final, It started working again.

**Comment by jchambers** [comment]
Can you please provide more information? In particular:

- What version of Pushy are you using?
- What version of Netty are (were) you using?
- How often does this happen? Is it every time?
- Was it working before and then stopped working?

Thanks.

**Comment by anuraggupta** [comment]
It was happening everytime. I tried restarting JVM/application , my laptop, connect with office VPN , connect without VPN ... All failed. Then I saw the PR's that went into 0.13.9 and tried by downgrading Netty version to previous version used by pushy

**Comment by jchambers** [comment]
Okay; this is almost certainly not a Pushy-specific issue, but let's try to narrow it down all the same. Could you please try the versions of Netty between 4.1.32 and 4.1.37 and see if you can find the specific one where this becomes a problem?

**Comment by dadangeuy** [comment]
this error appear in my app after 1 month. i run my app using docker, and i figure out that the dns is giving an inactive apns server. you can check it out by running `nmap -p 443 api.push.apple.com`, the result should be like this:
```
PORT    STATE SERVICE
443/tcp open  https
```
in my case, specifying my docker app to use google dns (`8.8.8.8` and `8.8.4.4`) solve it.

**Comment by jchambers** [comment]
Folks, it sounds like the problem here is outside of Pushy's control. I'm going to close this issue for now. If anybody discovers new information that suggests there's action we can take, please leave a comment here and we'll gladly revisit the issue.
