### ISSUE TITLE
Facing failed to build a Http2ConnectionHandler when trying to send a push notification

### ISSUE THREAD

**Issue by Pendejooo** [relayrides/pushy#726]
Hi,

I'm currently implementing push notification integration.

I've added in my pom.xml : 

```xml
        <!-- pushy dependency for push notifications -->
        <dependency>
            <groupId>com.turo</groupId>
            <artifactId>pushy</artifactId>
            <version>0.13.9</version>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.25.Final</version>
            <scope>runtime</scope>
        </dependency>
```

Here's my PushNotificationService class : 

```java
@Service
public class PushNotificationService {

    private final Logger log = LoggerFactory.getLogger(PushNotificationService.class);

    @Autowired
    PushNotificationConfig pushNotificationConfig;

    @Autowired
    Environment env;

    public void sendPushNotification(String userMobileDeviceToken) throws IOException {
        Future sendNotificationFuture = pushNotificationConfig.getApnsClient().sendNotification(buildPushNotification(userMobileDeviceToken));

        sendNotificationFuture.addListener((GenericFutureListener<Future<PushNotificationResponse>>) future -> {
            // When using a listener, callers should check for a failure to send a
            // notification by checking whether the future itself was successful
            // since an exception will not be thrown.
            if (future.isSuccess()) {
                final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse =
                    future.getNow();

                if (pushNotificationResponse.isAccepted()) {
                    log.debug("Push notification accepted by APNs gateway.");
                } else {
                    log.warn("Notification rejected by the APNs gateway: " +
                        pushNotificationResponse.getRejectionReason());

                    if (pushNotificationResponse.getTokenInvalidationTimestamp() != null) {
                        log.info("\t…and the token is invalid as of " +
                            pushNotificationResponse.getTokenInvalidationTimestamp());
                    }
                }
            } else {
                // Something went wrong when trying to send the notification to the
                // APNs gateway. We can find the exception that caused the failure
                // by getting future.cause().
                log.error(future.cause().getMessage(), future.cause());
            }
        });
    }

    private SimpleApnsPushNotification buildPushNotification(String userMobileDeviceToken) {

        ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
        payloadBuilder.setAlertBody("Example!");
        payloadBuilder.setAlertSubtitle("Example subtitle !");

        final String payload = payloadBuilder.buildWithDefaultMaximumLength();
        final String token = TokenUtil.sanitizeTokenString(userMobileDeviceToken);

        return new SimpleApnsPushNotification(token, "com.example.myApp", payload);
    }


}

```
And i have a push notification config class to load an ApnsClient based on certificate/password. This is working as i'm ready ton instatiate it and send a push notification.

This error comes after sending push :

```
15:58:24.586:[XNIO-2 task-1]:INFO:c.turo.pushy.apns.ApnsClientBuilder:Native SSL provider is available; will use native provider.
15:58:46.918:[nioEventLoopGroup-2-1]:WARN:i.n.util.concurrent.DefaultPromise:An exception was thrown by com.turo.pushy.apns.ApnsChannelFactory$1$1.operationComplete()
java.lang.IllegalStateException: failed to build a Http2ConnectionHandler
	at io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder.buildFromCodec(AbstractHttp2ConnectionHandlerBuilder.java:482)
	at io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder.buildFromConnection(AbstractHttp2ConnectionHandlerBuilder.java:471)
	at io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder.build(AbstractHttp2ConnectionHandlerBuilder.java:438)
	at com.turo.pushy.apns.ApnsClientHandler$ApnsClientHandlerBuilder.build(ApnsClientHandler.java:143)
	at com.turo.pushy.apns.ApnsChannelFactory$1$1.operationComplete(ApnsChannelFactory.java:149)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1740)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1409)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1273)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:500)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:439)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: io.netty.handler.codec.http.HttpResponseStatus.codeAsText()Lio/netty/util/AsciiString;
	at io.netty.handler.codec.http2.Http2ConnectionHandler.<clinit>(Http2ConnectionHandler.java:72)
	at com.turo.pushy.apns.ApnsClientHandler$ApnsClientHandlerBuilder.build(ApnsClientHandler.java:136)
	at com.turo.pushy.apns.ApnsClientHandler$ApnsClientHandlerBuilder.build(ApnsClientHandler.java:89)
	at io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder.buildFromCodec(AbstractHttp2ConnectionHandlerBuilder.java:478)
	... 34 common frames omitted
```

I'm using java 8 and i've added dependencies through maven. Maybe i'm missing something on netty configuration but didn't find anything related to that kind of error.

Thanks,
Tiago.

**Comment by jchambers** [comment]
That definitely sounds like some kind of strange Netty version mismatch. I'm really not sure what to make of the problem, but I'm confident it's not specific to Pushy. As a generic suggestion, I'd recommend clearing your Maven cache and trying again.

All that said, I don't think there's anything we can do or change on our end to solve this problem for you, and so I'm going to close this ticket for now.
